### ISSUE TITLE
Should rmsd be PBC-aware?

### ISSUE THREAD

**Issue by jhenin** [colvars/colvars#102]
Right now the rmsd cvc is calculated using plain distances. I can't see a downside for making it PBC-aware .

**Comment by giacomofiorin** [comment]
Me neither, but the computation of the alignment matrix deals with absolute coordinates (minus the center of geometry).

**Comment by jhenin** [comment]
To be properly PBC-aware, we'd need to apply the rotation matrix to the cell basis vectors. More involved than we want to get for now.
