### ISSUE TITLE
to minimum image or not to minimum image

### ISSUE THREAD

**Issue by akohlmey** [colvars/colvars#11]
After the issue with teaching fix colvars to use unwrapped instead of the "normal" (for LAMMPS) wrapped coordinates, there is now the question, how to overall handle the situation for when to compute the minimum image distance of two atoms (e.g. for bond, angles, dihedrals etc.) or not. this issue came up a while ago within LAMMPS with the following outcome: in most of the cases, it doesn't make a difference, however, in some corner cases, it does and there it would be better to not compute the minimum image.
the cases that then showed inconsistent before/after results all had bad input data (i.e. wrapped starting coordinates with bonds stretching across the box).

so the question is, what policy/convention should be adopted by colvars? it is somewhat arbitrary and it think it is most important to be consistent. with that in mind i plan to completely drop the option to use wrapped coordinates in fix colvars and present users with a single consistent view on how colvars are applied. even it it is no effort to leave the option in, it just confuses the wrong people and there is not much to gain from it.

**Comment by giacomofiorin** [comment]
The solution to this old-ish open issue is to allow the user to specify which colvars must take into account periodic boundary conditions by minimum image (see #65)
