### ISSUE TITLE
Idea: turn extended Lagrangian into separate colvar

### ISSUE THREAD

**Issue by jhenin** [colvars/colvars#113]
The idea:
- extended-Lagrangian colvars would have no components, and no value besides the extended variable
- coupling between the extended DOF and the actual colvar would be a separate bias
- this bias would be a new restraint: a harmonic coupling between two colvars (would have more general uses)

Benefits:
- no separate implementation of the harmonic coupling bias
- as a result, coupling could be customized, made time-dependent, other than harmonic, etc.
- no need for special tricks to apply forces to one degree of freedom or the other
- no need for special tricks to access one value or the other
- paves the way for lambda-dynamics, implemented as a bias on the extended colvar (no special CVC needed)

Downsides:
- more verbose input needed to set it up, although that could be automated for backwards-compatibility, like walls
- ABF would have to get some info from the "real" colvar to perform eABF properly, so a link needs to be provided. The extended colvar could have a property like "coupleToColvar".

**Comment by giacomofiorin** [comment]
I like the idea overall, but I'd like to avoid linking two variables together directly.  If you write down the list of info items that the extended colvar needs from the real one, can that be communicated by the bias?

**Comment by jhenin** [comment]
I entirely agree that one colvar taking directly to another colvar is contrary to the overall design.

Either way though, initially ABF would know only its target variable, and would need to get a reference to the other one. If that info is given by the coupling bias, then ABF will need a reference to that bias first, then get the info on the original colvar from the bias. ABF has no need to talk to that bias otherwise. So it seems more direct to jump directly from one colvar to the other.

For one colvar to know the name of the other seems minimally invasive to me: it doesn't significantly infringe on the design of the module. In that sense, communication between biases is not much cleaner than between colvars.

**Comment by giacomofiorin** [comment]
It does create a dependency that makes it less than easy to split up work across threads.  I'm OK with it for as long as you rewrite the SMP work scheduler.

**Comment by jhenin** [comment]
After some thinking, I think it fits well within the current workflow, including SMP. Colvars are all calc'ed first, then bias forces are calculated (the coupling force uses the value of both colvars at time t), and finally the extended system variable is integrated to t+dt in update_forces_energy.

**Comment by jhenin** [comment]
Among the info that would need to be passed to the extended colvar : periodicity. The bias coupling both colvars would have to use the right difference function. Same with a bias acting on the extended colvar.
