### ISSUE TITLE
Empty PDFs reference manuals

### ISSUE THREAD

**Issue by rbberger** [colvars/colvars#114]
@giacomofiorin if you look at any of the 3 reference manuals on http://colvars.github.io/, they only include two pages. The title page and an empty table of contents. I just tried out building the pdfs and it works on my machine. Something must be wrong when updating the website. 

Best,
Richard

**Comment by jhenin** [comment]
Thank you for the report! That should be fixed now.

**Comment by giacomofiorin** [comment]
@rbberger Thanks for reporting!
