### ISSUE TITLE
Distance_inv creates scalable atom groups

### ISSUE THREAD

**Issue by jhenin** [colvars/colvars#118]
More precisely, it inherits them from distance, because distance has the feature f_cvc_com_based, which is not correct for distance_inv.

For the sake of robustness, when atom groups are constructed, the state of f_cvc_com_based should be already correct. This is not possible in the case of inheritance.

Possible solutions:
- remove distance_inv's inheritance from distance
- turn off scalable feature after the fact

I tend to favor the first option. To limit code redundancy, a more generic parent class could be created. Or the CVC class could be enriched with some more mechanics for handling atom groups.

**Comment by giacomofiorin** [comment]
Fixed by fd74453
