### ISSUE TITLE
Change numerical tolerance criteria in regression tests?

### ISSUE THREAD

**Issue by giacomofiorin** [Colvars/colvars#123]
The current version of LAMMPS (23Jun2017) does not reproduce the reference *unbiased* MD trajectories of the regression tests.  **Note:** the test inputs use already an NVE ensemble.  The divergence happens at step 38 of the unbiased run, or earlier in other runs (but never in the first 10 steps).  There are no differences that I can see in the CHARMM pair styles functions between the two LAMMPS versions.

A similar problem happened already when switching from NAMD 2.10 to 2.11.  It's safe to say that this has not happened again in NAMD only due to its slower development pace compared to LAMMPS.

I think that we need to integrate the numerical tests into the inputs themselves, or subtract the unbiased Cartesian-space trajectory (which may change) from the observed one, and use the current stringent criteria only on the colvars' values and their associated atomic forces (but not on the total forces).

This will take some time.

**Comment by jhenin** [comment]
I looked into what kind of relative and absolute errors we get in the LAMMPS tests. The worst happens in this file: `000_distancevec-fitgroup_harmonic-dvec-fixed/test.colvars.traj`
where the relative errors are 5e-4 at timestep 18.Then it goes down for the next two timesteps.

We could consider the relative error acceptable and set the tolerance to 1e-3. Certainly sufficient to catch most bugs, but maybe not the more subtle ones.

To me the change in Cartesian coordinates between versions seems unacceptably large - how about reducing the MD timestep in those tests?

**Comment by giacomofiorin** [comment]
Well, 1e-3 is really coarse, it will definitely ignore the subtler issues such as missing fit gradients and such. No way for me with that.

Decreasing the time step by one order of magnitude may do the trick for now.

Note, however, that we keep coming back to this problem.  Do not be surprised if this shows up again in the future.

**Comment by giacomofiorin** [comment]
Unfortunately using `timestep 0.1` (fs) did not fix the issue, there are still failures for:
```
000_distance-extended
000_distancevec-fitgroup_harmonic-dvec-fixed
000_orientation-fitgroup_harmonic-ori-fixed
```
Admittedly the second and third could be unstable due to lacking fit gradients.  For distance-extended, perhaps the spring settings are still too stiff?  I put the updated ones in:

https://github.com/colvars/colvars/tree/lammps-regtests

**Comment by jhenin** [comment]
With CUDA-enabled NAMD 2.12, the regtests fail _en masse_. You're right, we're not done with this problem.

**Comment by giacomofiorin** [comment]
This is why I added one regtest for an unbiased simulation (we've been there already once with the NAMD CPU code).  If anything, I believe NAMD was stable at the level of precision that we use mostly because the serial CPU code has hardly been modified in the last few years.  If a MD code has had some work done on it, we need to accept that the trajectory will diverge at the 11th or 12th digit even in so few steps.

We can try converting the runs into reruns, where the entire code flow can still be probed (e.g. from `loadforces` in NAMD or from the LAMMPS library interface).

**Comment by jhenin** [comment]
With the current NAMD, CPU version, I get 3 failed tests at 1e-7 relative error, but all succeed at 1e-6. As before, the CUDA version has errors above 1e-4.

An idea to handle these very variable levels of precision: testing with adaptive tolerance. That is, run tests at 1e-7, and for any tests that fail (hopefully not too many), run them again at 1e-6, etc. until 1e-3. then report the resolution at which each test succeeded, or complete failure.

**Comment by giacomofiorin** [comment]
Give it a try.  I am currently compiling NAMD with gcc 4.8 inside a container, and this seems to be stable enough for the time being.  Since the features in the library tests (especially those copied from the top-level `tests` folder) are code-independent, that test platform is equivalent to the others.  By the time the integrator code in NAMD changes again significantly, we will have available a test mechanism based on a rerun rather than a run.  In LAMMPS, that is already possible, and I just haven't configured it because there was no pressing need yet.

**Comment by jhenin** [comment]
Fair enough.
