### ISSUE TITLE
dPCA input question

### ISSUE THREAD

**Issue by MamtaMohan** [colvars/colvars#125]
Hi,

I am try to do Metadynamics using dPCA as collective variable.

I am not clear about VectorNumber input.

I used CARMA to generate input and this is my input file:

colvars: ----------------------------------------------------------------------
colvars: Initializing the collective variables module, version 2012-03-23.
colvars: # analysis = on
colvars: # colvarsTrajFrequency = 1000
colvars: # colvarsRestartFrequency = 1000
colvars: # colvarsTrajAppend = off [default]
colvars: The restart output state file will be "T4L72131_mBkdPCA1bar_out.restart.colvars.state".
colvars: The final output state file will be "T4L72131_mBkdPCA1bar_out.colvars.state".
colvars: The trajectory file will be "T4L72131_mBkdPCA1bar_out.colvars.traj".
colvars: ----------------------------------------------------------------------
colvars:   Initializing a new collective variable.
colvars:   # name = dpca72
colvars:   Initializing a new "dihedralPC" component.
colvars:     # componentCoeff = 1 [default]
colvars:     # componentExp = 1 [default]
colvars:     # period = 0 [default]
colvars:     # wrapAround = 0 [default]
colvars:     # psfSegID = PROA
colvars:     # vectorFile = carma.mBkdPCA1bar.eigenvectors.dat
colvars:     # vectorNumber = 1
colvars:     Error: wrong number of coefficients: 652. Expected 8 (4 coeffs per residue, minus one residue).
colvars:     If this error message is unclear, try recompiling with -DCOLVARS_DEBUG.
FATAL ERROR: Error in the collective variables module: exiting.

I would appreciate your response.

Mamta

**Comment by jhenin** [comment]
Either the file format produced by CARMA changed, or the atom definitions you provided to CARMA don't match those provided to colvars. Here colvars has detected only three residues, but it parses the CARMA file as containing much more data. How many residues did you analyze in CARMA?

**Comment by MamtaMohan** [comment]
Dear Jerome,

Thank you for your response.

I used all 164 residues of protein to generate dPCA eigenvector file via CARMA as an input for 'vectorFile'.

For 'vectorFile', it looks like after reading your question that input for 'vectorFile' need to be generated only for three residues which are given in the  residueRange. Is this correct?

My understanding is not clear about input for 'vectorNumber'.

In COLVAR documentation it says 'File containing dihedralPCA eigenvector(s). Acceptable Values: positive integer'. So I gave '1' to do pseudo-potential calculation only along 1st dPCA component. Is this input correct or I am suppose to provide a file?

I am not quiet sure which file I need to provide for 'vectorNumber'. I would appreciate your input.

I am listing my colvar file below. If you could point my mistakes I would truly appreciate it.

Mamta

colvar.conf
#
# MetaD Standard
# T4L72131 backbone dPCA
#
colvarsTrajFrequency    1000
colvarsRestartFrequency 1000
analysis                on

colvar {
name               dpca72
outputVelocity     on
outputAppliedForce on
runAve             on

dihedralPC {
residueRange   71 - 73
psfSegID       PROA
hBondCoeff     0.5
angleRef       88.0
angleTol       15.0
hBondCutoff    3.3
hBondExpNumer  6
hBondExpDenom  8
vectorFile     carma.mBkdPCA1bar.eigenvectors.dat
vectorNumber   1

metadynamics {
name                 metaD_BkdPCA1bar
colvars              dpca72
hillWidth            1.25331 # Default = 1.25331
hillweight           0.01    # Default = 0.01, higher number = faster =poor sampling
newHillFrequency     100     # Default = 100, lower numbers = faster = poor sampling
dumpFreeEnergyFile   yes
writeHillsTrajectory on
} 

}
}

**Comment by jhenin** [comment]
This line looks wrong:
> residueRange 71 - 73

You probably want
> residueRange 1 - 164

**Comment by MamtaMohan** [comment]
Thank you for your help.
