### ISSUE TITLE
Minor memory leak in init_xx_requires()

### ISSUE THREAD

**Issue by giacomofiorin** [Colvars/colvars#127]
This problem was observed by @akohlmey on all Colvars input tests, and is most likely due to `new`ed feature objects not being deallocated when an object is destroyed, because the vector containing them is a static member.  This won't likely present a problem in production runs, but it does generate a lot of output in Valgrind, making it difficult to identify more serious leaks.

A reference counter should do the trick, and the SMP locking won't present a major overhead, because the counter would be changed only at object construction/destruction.

**Comment by jhenin** [comment]
Reference counting is an option - the other is to make these regular members. Making that data static seems a little like frivolous optimization now.

**Comment by giacomofiorin** [comment]
I'm not sure it's frivolous, since each `feature` object contains multiple STL vector, including one vector of vectors.  At least a few `feature` objects for each parent object will have those vectors non empty.  The memory usage isn't much, but there is a lot of dereferencing going on.

One thing I realized by looking at this specific part of the dependency system is that the first part of `init_xx_requires()`, which sets up the vector of `feature` objects, may need an SMP lock.  (We may not be seeing race conditions because there are very few people using NAMD with CkLoop, and most Colvars uses in LAMMPS involve a small number of variables/components.)  But I would like to add more threaded regions, and probably the ideal arrangement would be a class-`static` vector of feature that is read-only everywhere except when it's initialized.

Can the `features()` accessor be made `const`, and only if the vector is empty use a non-`const` one to initialize?  Something like:
<pre>
  if (features().size() == 0) {
    for (i = 0; i < f_cvb_ntot; i++) {
      <b>modify_features()</b>.push_back(new feature);
    }
    ...
  }
</pre>

**Comment by jhenin** [comment]
One part is done - splitting the accessor into const and non-const version (9d5fdd5532e3b572ecaffc8a21a8d7eeb700c970). Now I realize this doesn't completely solve the concurrency issue. The refcount itself must be static data - if it is made a member of the features object, then touching the refcount will require using the non-const accessor. If it is a separate static member, changing it might entail race conditions as well. Ideas?

**Comment by giacomofiorin** [comment]
I would add `proxy->smp_lock()` and `proxy->smp_unlock()` around the reference increment.  But for this to work there should be a separate reference counter for each class that derives from `colvardeps`, but not `colvardeps` itself.  It also looks like the increment/decrement could go in the constructor/destructor.

**Comment by jhenin** [comment]
Fixed by 1619e0e957f924028af12ce217eaec8029fd4f39.
