### ISSUE TITLE
new colvars in studying phase transitions

### ISSUE THREAD

**Issue by qzhu2017** [Colvars/colvars#128]
Dear All,

I am interested in studying the pressure induced phase transition by enhanced sampling method. It has been found the use of cell vectors and  Steinhardt order parameters as the colvars could be very useful to drive the solid phase transition (for more details, see the following papers). 
http://www.nyu.edu/classes/tuckerman/pchem/extras/PhysRevLett.107.015701.pdf
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4048450/

I wonder how I can customize the cell vectors in the module of Colvars and run metadynamics style simulation in LAMMPS?

**Comment by giacomofiorin** [comment]
I spoke today with @athomps today, the Steinhardt parameters implemented in LAMMPS only provide analysis capability (they are not scaled near the cutoffs, and lack atomic derivatives).  If you are planning on using them in LAMMPS with Colvars, you could look into porting the code from PINY_MD (papers that you cite) into a `fix`.  If you can do that, I can help you hooking this fix to Colvars.

At any rate I will look into accessing `fix npt` for the unit cell vectors.
