### ISSUE TITLE
Question: Eigen vector input

### ISSUE THREAD

**Issue by MamtaMohan** [Colvars/colvars#129]
Dear Colvar Team,

I would like to use Eigenvector as an input to Colvar module.

To generate input : After NM analysis in gromacs I converted respective eigenvector file in .trr format to .xyz format and extracted required eigenvector. I used catdcd for conversion and extraction of eigenvector.

I understand it might be trivial question to you but I would appreciate if you could point any issue related to this.

I would appreciate your response.
Mamta

**Comment by giacomofiorin** [comment]
Hello Mamta, your procedure looks OK.  Follow the syntax specified in the documentation (specifically `vectorFile`).  If you are unsure that everything works as expected, why don't you try a simple example with only two atoms and an eigenvector like the following?
```
0 0 1
0 0 -1
```
It should give you the difference in Z coordinates of the two atoms.

**Comment by MamtaMohan** [comment]
Thank you.
