### ISSUE TITLE
Query: Colvar PC use

### ISSUE THREAD

**Issue by MamtaMohan** [Colvars/colvars#131]
Dear Colvar Team,

I am using in section dPCA's 'pc1' as colvar.

For Colvar grid parameters :  lowerBoundary, upperBoundary and for width, I am using lowest value of pc1, highest value of pc1 and difference between two values as width. These are my values:

awk '{print $2}' carma.dPCA.fluctuations.dat | sort -n | tail -1 
1.5816865
 
awk'{print $2}' carma.dPCA.fluctuations.dat | sort -n | head -1
-2.7210100

This is what I gather for PC1:

Maximum value :  1.5816865 -- upperBoundary
Minimum  value : -2.7210100 -- lowerBoundary
Range               :   1.5816865 - (-2.7210100) = 4.3026965 --width or fluctuation amplitude

Regarding _width_, I have bit of confusion. 

Colvar documentation states :
width : _Metadynamics (6.3) uses it to set the width of newly added hills._ In other cases, it is simplest to keep the default value of 1, so that harmonic force constants are provided in their usual physical unit. When a non-unity width is required by the application, the optimal value is application-dependent, but can often be thought of as a user-provided estimate of the ﬂuctuation amplitude for the colvar. _In those cases, it should generally be set smaller than or equal to the standard deviation of the colvar during a very short simulation run._ 

_Does it mean to provide width: I should first calculate StdDev of PC1 (I would imagine it will be for matrix) and I should provide that value as width which is less than or equal to Standard Deviation of PC1._ 

Does it sound right to you?

Or Can I use Range calculated above as width. 

I would appreciate you response.

Mamta

**Comment by jhenin** [comment]
My understanding is that you're going to run metadynamics on this - then this is a metadynamics question, not a question on colvars, and then this is not the right place to ask. If not, please mention what usage you will make of this colvar.

**Comment by MamtaMohan** [comment]
I am going to run Metadynamics. 

Please advise me about right forum.

**Comment by MamtaMohan** [comment]
Thank you.

I will do so.
