### ISSUE TITLE
subtractAppliedForce with extendedlagrangian

### ISSUE THREAD

**Issue by fhh2626** [Colvars/colvars#137]
Hello Guys,
I would like to ask why subtractAppliedForce cannot work with extendedlagrangian now. The combination of the two option is extremely useful in eABF-based simulation. For example, the follow config describes an eg-ABF simulation with CZAR estimator:

================================
colvars {
name dihedral_A
extendedlagrangian   on
subtractAppliedForce	on
...
}
colvars {
name dihedral_B
extendedlagrangian   on
subtractAppliedForce	on
...
}

\# eg-ABF simulation
\# two independent 1D biasing forces
abf {
	fullSamples 500
	colvars dihedral_A
}
abf {
	fullSamples 500
	colvars dihedral_B
}
\# only collect spring length and calculate gradients by estimators
abf {
	fullSamples 200
	colvars dihedral_A dihedral_B
	applyBias no
}

This config works well with NAMD 2.12, but does not in later version. Is it possible to make the combination of the two option available again?

Thanks a lot!
Haohao

**Comment by jhenin** [comment]
Hi Haohao,

Good point. The reason I made the change is that subtractAppliedForce means that the bias is subtracted from the total force, but with extended Lagrangian there is no total force measurement, the harmonic force serves as a proxy for that.

As a result it was not clear to me how this should be cleanly defined, that is, from what term that biasing force should be subtracted. I admit that I did not think of the egABF case then.

I will see how I can restore this functionality while making sure it always does something sensible.

Jerome

**Comment by jhenin** [comment]
Strictly speaking, the incompatibility was enforced by commit 06dce272d8178748fa6c0d974553deac988676e4. That can easily be reversed, however, my impression is that the code that would give correct results is missing. I am unsure how the version from NAMD 2.12 gave sensible results.

**Comment by HanatoK** [comment]
In commit https://github.com/Colvars/colvars/commit/9c34a0ad2cfb3a1b3399ea0ca98869acc345361d the `ft_reported` was also changed.
In my test, only making subtractAppliedForce on and `ft_reported = (-0.5 * ext_force_k) * this->dist2_lgrad(xr, x);` together can give correct results. I know ft_reported is the total force acting on the extended variable and it should be equal to f_ext, but I can't figure out the why `ft_reported = f_ext;` gives wrong results.

**Comment by jhenin** [comment]
Thanks @HanatoK (whoever you are), that's what I couldn't find because the commit message was incomplete.

I've undone those changes in commit fe389c90540e4353fd390698a95cb3c3fd32c48e, please let me know if it works for you @fhh2626 .

**Comment by fhh2626** [comment]
Thanks a lot @jhenin . It works for me. @HanatoK is my friend, who has implemented czar estimator in plumed.

**Comment by HanatoK** [comment]
@jhenin 
Thanks for fixing this issue. However, I still can't figure out why `subtractAppliedForce` works. Does CZAR always use the average spring forces to estimate the second term of gradients?

**Comment by jhenin** [comment]
@HanatoK : CZAR accumulates the value of `system_force` into `z_gradients`. And `system_force` comes from `update_system_force()` in colvarbias_abf.h, which fetches the colvars's `ft_reported` value (which is the external force + spring force), and subtracts the previous eABF force.

hence: if any other biasing forces besides eABF are applied to the coordinate, they will be taken into account in the CZAR PMF.
