### ISSUE TITLE
Data structure for general script subcommand 

### ISSUE THREAD

**Issue by giacomofiorin** [Colvars/colvars#138]
This is minor, because the script interface and its documentation are OK for now.  (Although I did forget to update the inline help string at the last edit).

My concern is that the `colvarscript` member functions are becoming long and complex, and would strongly benefit from collecting all the information for each subcommand (keyword, accessible syntax, help string, code execution) in a single object.  It would also be good to have each subcommand call its own function (C linkage).

The question is whether it's a good idea to sub-class `colvardeps::feature` or make a different class altogether for a script subcommand.

**Comment by jhenin** [comment]
What makes it slightly complicated is that the arguments to different subcommands have their own syntax. Right now this is separated in the colvar and bias subcommands, which have their own sub-subcommands. A generic interface that expresses these two, plus the other commands will need to be somewhat rich.

Thinking about it, `cv colvar X delete` could be rephrased internally as `cv delete_colvar X`, so we fall back to the `cv subcommand [parameters]` syntax. Then the common code of the `colvar` subcommand can be made a separate function that is called by the separate implementations of the colvar sub-subcommands.

I don't see the `feature` class as very helpful for that purpose.

**Comment by giacomofiorin** [comment]
I'm OK with keeping the syntax `cv colvar X <subcommand>`, particularly if this could be simplified by creating a Tcl proc, much like in the `atomselect` syntax.  I'm not sure that's the perfect approach, but its adoption is so wide that consistency would be a plus.  So we can have:
```
set X [cv colvar X]
${X} get value
```
and so on.  I haven't moved forward after 11c138f but that's what I was going for.  So the syntax of parsing one subcommand would still be uniform. 

At any rate, OK with not reusing the `feature` class, I wanted to hear your thoughts considering planned changes to it.
