### ISSUE TITLE
[ Feature Request ] Accessing the running average of a colvar from the scripting interface

### ISSUE THREAD

**Issue by flblanc** [Colvars/colvars#142]
Dear colvars developers,

In the case where the `analysis` flag is turned on, would it be possible to make the computed statistical quantities (such as the correlation function or the running average) accessible from the scripting interface? Essentially, something like:

`cv colvar MyColvar running_average` 

similarly to the existing `cv colvar MyColvar value`. 

If it is not possible, would you be kind enough as to give me some ideas on how to "hack" this feature, possibly using an external tcl script? 

Thank you very much in advance,

Florian Blanc

**Comment by jhenin** [comment]
Looking at this made me notice issue #143.

That said, implementation for the running average was simple (5752af75263c8b5fe5168309faa3279abe5ada49). It's not as simple for correlation functions, that are calculated as a series of values.
