### ISSUE TITLE
Running average calculation segfaults when using multiple runs in NAMD

### ISSUE THREAD

**Issue by jhenin** [Colvars/colvars#143]
I think this is caused by the function calc_runave() being called twice for the same timestep (end of a run and beginning of the next run).

**Comment by giacomofiorin** [comment]
FYI you don't need to close this manually, because PR #194 mentions in its description that it fixes this issue, which would then get closed automatically upon merging.  This would be of course critical only in large repositories, but it is otherwise useful for distracted people :-)
