### ISSUE TITLE
[lammps-Colvars] harmonicWalls

### ISSUE THREAD

**Issue by HuadaLian** [Colvars/colvars#144]
Hi,

I am using the lammps-11Aug17 for calculation of the potential of mean force. 

The following is my colvars configuration file, in order to test colvar module with lj fluid, 

```
colvarsTrajFrequency    100000
colvarsRestartFrequency 2000000

colvar {
   name dist
   width   0.1 
   lowerBoundary  0.8100
   upperBoundary  6.0100 
   distance {
     group1 { atomNumbers { 1 }  }
     group2 { atomNumbers { 2 }  }
   }
}

metadynamics {
   name                 mtd 
   colvars              dist 
   hillWeight           0.2  
   newHillFrequency     100000
   outputEnergy         on 
   writeFreeEnergyFile  on 
   keepFreeEnergyFiles  on 
} 

harmonicWalls{
   colvars   dist
   lowerWalls  0.81000
   upperWalls  6.0100 
} 
```

The outcoming error message is :

>  keyword "harmonicWalls" found without configuration.

The example in lammps/example/USER/colvars/ are all running well, thus I believe it has nothing to do with compilation. 

In my understanding, colvar block only defines a variable but won't affect simulation, the metadynamics block will add bias only in colvar's region. To restrict the colvar, I'd like to add one more bias "harmonicWalls" to confine it in a certain region. 

Looking forward to any advice. 

Thanks.

**Comment by giacomofiorin** [comment]
Hi, does it work if you add a space after `harmonicWalls`?  The space is needed to identify the word correctly.

**Comment by giacomofiorin** [comment]
On second thought, I notice that you edited the issue after submitting it.  In my email notification, I received from you the following:
```
harmonicWalls{
configuration{
colvars dist
lowerWalls 0.81000
upperWalls 6.0100
}
}
```

Can you post the exact content that you are using?

**Comment by HuadaLian** [comment]
Thank you so much. It is the issue of that missing space. I didn't notice such a trivial point.
