### ISSUE TITLE
Add DX file parser

### ISSUE THREAD

**Issue by jhenin** [Colvars/colvars#145]
Will be useful mostly for 3D grids that are cumbersome in multicol format.

**Comment by giacomofiorin** [comment]
The OpenDX format is pretty flexible.  It may be a good idea to restrict to
the dialect used by VMD and NAMD, but even their two parsers are not
identical.

**Comment by jhenin** [comment]
Good point. The only part of NAMD I'm aware of that reads DX is gridForces. Is there anything else? Does NAMD write DX files?

**Comment by giacomofiorin** [comment]
No gridforces is the only part and it's read only.  Gridforces has also its
specialties compared to the VMD reader so it's not clear to me which one to
be consistent with.

**Comment by giacomofiorin** [comment]
I actually forgot something pretty important here:
```
4d07cc3 2015-05-14 Add write_opendx method for colvargrid [Giacomo Fiorin]
```
If you think necessary, try writing a `read_opendx` function that matches it, using `read_raw()`, since the writer uses `write_raw()`.  The format that I set there is pretty much the minimum common denominator between the cases discussed earlier.

**Comment by jhenin** [comment]
Sure, I'm starting to use this (on a private branch for now). That's why I am thinking of the parser. Yes, the first requirement would be to read files written by that code!

**Comment by jhenin** [comment]
No time to work on this, setting as low priority.
