### ISSUE TITLE
Inconsistency in custom function dependency handling for periodic components

### ISSUE THREAD

**Issue by giacomofiorin** [Colvars/colvars#146]
Bug report from Nicolas Künzel <nicolas.kuenzel@uni-rostock.de>

The dependency system tries to enable the "homogeneous" feature when the colvar's value is scalar, but does not when the colvar has a higher dimension.

To reproduce, use the `customFunction` regtest, and replace the `distance` component with a `dihedral` one.  The 2-D variable is allowed, but a 1D variable isn't.

**Comment by jhenin** [comment]
Thanks. Fixed by 4413972ed5e9a48719c1f2e8d96511425ec7c1cf.
