### ISSUE TITLE
Question about post-processing 2D extended ABF gradient

### ISSUE THREAD

**Issue by flblanc** [Colvars/colvars#149]
Dear _colvars_ developers and users,

I have recently started to use 2-dimensional extended ABF calculations. As you know with 2D calculations, one needs to use the `abf_integrate` program to compute the PMF from the gradient. 

This program also requires the `.count` files and takes it with the same prefix as the `.grad` file (with no possibility to specify otherwise to the best of my knowledge). 
Now, with eABF, one is more interested in obtaining the CZAR corrected PMF, whose associated gradient is in the file `prefix.czar.grad`. In this case, I believe (but I may be mistaken) that the relevant count numbers are the ones stored in the `prefix.zcount` file. 

This means that to obtain the 2D CZAR corrected PMF, one needs to do first:

`cp prefix.zcount prefix.czar.count`

then

`abf_integrate prefix.czar.grad` 

First, is that correct ? 

Second, would it be possible to modify `abf_integrate` so that one can pass explicitly the `.count file` as an argument? I know it is a tiny detail, but it would be a "quality-of-life" improvement. 

Thanks in advance, 

Florian Blanc

**Comment by jhenin** [comment]
Dear Florian,

thanks for this remark. I just pushed commit 9798277 that makes abf_integrate detect CZAR gradients and open the zcount file on its own. Note that the recently added on-the-fly Poisson integration (still experimental, but it works well in my hands) will make abf_integrate all but obsolete soon. Feel free to give it a try and send feedback!

Best,
Jérôme
