### ISSUE TITLE
writeHillsTrajectory is default to on in the reference manual but actually default to off

### ISSUE THREAD

**Issue by HanatoK** [Colvars/colvars#150]
The documentation says `writeHillsTrajectory` is default to on but the code in colvarbias_meta.cpp is
`get_keyval(conf, "writeHillsTrajectory", b_hills_traj, false);`
writeHillsTrajectory is turned off in default.

**Comment by giacomofiorin** [comment]
I fixed the typo in 5d36413.  Thanks for reporting it!
