### ISSUE TITLE
Scripting interface to change component coeffs/exp

### ISSUE THREAD

**Issue by jhenin** [Colvars/colvars#151]
Right now this requires deleting and recreating a colvar. A fast interface for this would be useful for automated colvar refinement within some parameter space.

**Comment by giacomofiorin** [comment]
After construction, you could call the base-class `init()` function:
```
error_code |= cvcs[i]->init(new_config_string);
```
and `new_config_string` would only contain the redefinition of those two parameters.

Commit `81d391f` implements `init()`, you just have to add the call for it.

For now this works only for the base class, but it can be easily extended to the derived CVCs, just like I have set up for `colvarbias` and its derivatives.  The recommendation is to have the calls to `get_keyval()` use the *current* value of the parameter as default, and put all the defaults in the constructor.  Eventually, I'd like to eliminate the overloaded constructor altogether, and leave only the one with no arguments.

**Comment by jhenin** [comment]
Well, now I can better appreciate the scope of this comment, and I fully agree with it.

**Comment by giacomofiorin** [comment]
This turned out to require some more plumbing, so I took it over. The feature is implemented as of fb67424, with the command named `modifycvcs`
