### ISSUE TITLE
The size of a scalable atom group is always zero.

### ISSUE THREAD

**Issue by HanatoK** [Colvars/colvars#153]
In colvaratoms.cpp only the non-scalable atom groups invoke `add_atom(cvm::atom)`. The atoms vector of a atom_group object is always empty when the atom group is considered as scalable.
This problem renders the `ref2` option in the distanceZ colvar useless because the code in `if (ref2 && ref2->size()) { ... }` never runs.
According to commit a9020061800599ee5c52492cc3c58fe356fb8f6e, the atom groups are not really marked as scalable before that commit, so NAMD 2.12 is not affected and the latest NAMD with the latest colvars is affected.

**Comment by jhenin** [comment]
Thank you for this report! I am looking into it.

**Comment by jhenin** [comment]
Fixed by c92d36963b4b4b7d9885349e0e5c1fe8b6c494d3. Thanks again.
