### ISSUE TITLE
A possible memory leak in the output stream of the NAMD proxy.

### ISSUE THREAD

**Issue by HanatoK** [Colvars/colvars#154]
In the latest version of NAMD I find its memory usage increases every time when Colvars is writing output files. The huge memory consumption has invoked the OOM killer to kill the NAMD process.
After some debugging with valgrind I suspect the memory leak is in colvarproxy_namd.C. In the `colvarproxy_namd::output_stream`, it calls `ofstream_namd *os = new ofstream_namd(output_name.c_str(), mode);` but the pointer isn't deleted in `colvarproxy_namd::close_output_stream`, so I add `delete (*osi);` in `colvarproxy_namd::close_output_stream`
The modified code is:
```
int colvarproxy_namd::close_output_stream(std::string const &output_name)
{
  std::list<std::ostream *>::iterator osi  = output_files.begin();
  std::list<std::string>::iterator    osni = output_stream_names.begin();
  for ( ; osi != output_files.end(); osi++, osni++) {
    if (*osni == output_name) {
      if (((ofstream_namd *) *osi)->is_open()) {
        ((ofstream_namd *) *osi)->close();
      }
      delete (*osi);
      output_files.erase(osi);
      output_stream_names.erase(osni);
      return COLVARS_OK;
    }
  }
  return COLVARS_ERROR;
}
```
After adding the delete line, the memory usage looks stable when writing files.

**Comment by giacomofiorin** [comment]
Thanks for identifying and reporting it!

Out of curiosity, what kind of simulation configuration generated the very large memory consumption?

**Comment by HanatoK** [comment]
@giacomofiorin 
The simulation system has only one atom with a self-defined potential by tclforces. I have uploaded the colvars input to https://gist.github.com/HanatoK/01ac17232b07c158e9146a43c26bb4ff
By the way, why not use the unique_ptr smart pointer? It looks a good solution to this kind of issues.

**Comment by giacomofiorin** [comment]
NAMD, LAMMPS and VMD still support many pre-C++11 platforms.  There is talk about requiring C++11 for LAMMPS, which has a relatively more modern code base (2004 and later), but for NAMD and VMD that day is still quite far.
