### ISSUE TITLE
Inconsistency of the extended CVs when running NAMD with TCL loop

### ISSUE THREAD

**Issue by HanatoK** [Colvars/colvars#159]
When running NAMD through TCL loop in the configuration file like:
```
colvars   on
colvarsConfig   co.in

for {set i 0} {$i < 500000} {incr i} {
    run 1
}
```
Extended Lagrangian is turned on in the co.in. The output trajectory of colvars shows:
```
# step         CHdihedral            r_CHdihedral          fa_CHdihedral          
           0    5.43113623342571e+01  5.43113623342571e+01  0.00000000000000e+00  
           1    5.40748413128293e+01  5.43113941845566e+01  0.00000000000000e+00  
           1    5.40748413128293e+01  5.43111936874766e+01  0.00000000000000e+00  
           2    5.38391593767274e+01  5.43110502384999e+01  0.00000000000000e+00  
           2    5.38391593767274e+01  5.43113443009401e+01  0.00000000000000e+00  
           3    5.36238565128614e+01  5.43120722127785e+01  0.00000000000000e+00  
           3    5.36238565128614e+01  5.43117761218542e+01  0.00000000000000e+00  
           4    5.34417403550690e+01  5.43117948355403e+01  0.00000000000000e+00  
           4    5.34417403550690e+01  5.43118051273506e+01  0.00000000000000e+00  
```
I expect the position of extended CV should remain the same when the next turn of TCL loop starts. For example, the first four line should be:
```
# step         CHdihedral            r_CHdihedral          fa_CHdihedral          
           0    5.43113623342571e+01  5.43113623342571e+01  0.00000000000000e+00  
           1    5.40748413128293e+01  5.43113941845566e+01  0.00000000000000e+00  
           1    5.40748413128293e+01  5.43113941845566e+01  0.00000000000000e+00  
```

**Comment by jhenin** [comment]
Thank you @HanatoK for this report. Indeed, there seems to be an extraneous integration timestep for the extended coordinate. This would be unnoticeable when running a long trajectory, but becomes clear with `run 1`. I will look into this.

**Comment by jhenin** [comment]
The problem arises mostly because NAMD runs two timesteps when you call `run 1`, a repeat of the previous ts, and a new one. In your case, `run norepeat 1` might work, depending on what parameters you need to change between the run statements.

Anyway, I've added a mechanism to revert the latest extended integration ts if it turns out the same timestep is requested again. 
See 127375e13c90a8adaed774296ff4c3ad785ac416
