### ISSUE TITLE
Found a bug in USER-COLVARS package in LAMMPS (16Mar18)

### ISSUE THREAD

**Issue by YOSHIZAWAK** [Colvars/colvars#163]
Dear colvars developpers,

I am from RIST (Research Organization for Information Science and Technology), Japan. 
HPCI (High Performance Computing Infrastructure) System including "K computer"
 provides high performance computing services for scientists and researchers around the world. 
User selection and support is conducted by RIST in HPCI.

I am installing LAMMPS on K computer.
After adding USER-COLVARS package to LAMMPS (16Mar18),
I have run a test on K computer.
I get the following runtime error.

[a05-008:03456] *** Process received signal ***
[a05-008:03456] Signal: Segmentation fault (11)
[a05-008:03456] Signal code: Address not mapped (1)
[a05-008:03456] Failing at address: 0x10
[a05-008:03456] [ 0] /opt/FJSVxosmmm/lib64/libmpgpthread.so.1(__pthread_
mutex_init+0x38)[0xffffffff126921e8]
[a05-008:03456] [ 1] /opt/FJSVtclang/GM-1.2.0-24/lib64/libfj90i.so.1(omp
_init_lock+0x14)[0xffffffff01523dd4]
[a05-008:03456] [ 2] ./lmp_K_mpi_omp[0x2579c6c]
...
[a05-008:03456] [14] /lib64/libc.so.6(__libc_start_main+0x194)[
0xffffffff1313381c]
[a05-008:03456] [15] ./lmp_K_mpi_omp[0x12d8ec]
[a05-008:03456] *** End of error message ***
[ERR.] PLE 0017 plexec The process terminated with the signal.(rank=0)(
nid=0x03020018)(sig=11)

I found a bug in lammps-16Mar18/lib/colvars/colvarproxy.cpp
I suggest a modified file colvarproxy-16Mar18_RIST.cpp
（I will make similar proposals in LAMMPS (16Jul18)）
Please consider that.

The difference between the two files is shown below in LAMMPS (16Mar18)
・colvarproxy-16Mar18_ASIS.cpp: packages intact in  LAMMPS (16Mar18)
・colvarproxy-16Mar18_RIST.cpp: Modified version by RIST in  LAMMPS (16Mar18)
$ diff -u colvarproxy-16Mar18_ASIS.cpp colvarproxy-16Mar18_RIST.cpp
--- colvarproxy-16Mar18_ASIS.cpp	2018-07-21 05:06:02.000000000 +0900
+++ colvarproxy-16Mar18_RIST.cpp	2018-07-21 05:06:02.000000000 +0900
@@ -223,6 +223,7 @@
   omp_lock_state = NULL;
 #if defined(_OPENMP)
   if (smp_thread_id() == 0) {
+    omp_lock_state = malloc(sizeof(omp_lock_t)); // RIST
     omp_init_lock(reinterpret_cast<omp_lock_t *>(omp_lock_state));
   }
 #endif

The difference between the two files is shown below in LAMMPS (16Jul18)
・colvarproxy-16Jul18_ASIS.cpp: packages intact in  LAMMPS (16Jul18)
・colvarproxy-16Jul18_RIST.cpp: Modified version by RIST in  LAMMPS (16Jul18)
$ diff -u colvarproxy-16Jul18_ASIS.cpp colvarproxy-16Jul18_RIST.cpp
--- colvarproxy-16Jul18_ASIS.cpp	2018-07-21 05:06:02.000000000 +0900
+++ colvarproxy-16Jul18_RIST.cpp	2018-07-21 05:06:02.000000000 +0900
@@ -289,6 +289,7 @@
   omp_lock_state = NULL;
 #if defined(_OPENMP)
   if (smp_thread_id() == 0) {
+    omp_lock_state = malloc(sizeof(omp_lock_t)); // RIST
     omp_init_lock(reinterpret_cast<omp_lock_t *>(omp_lock_state));
   }
 #endif

**Comment by giacomofiorin** [comment]
Thanks for reporting it!  You don't need to submit a fix for the same bug on the LAMMPS repository, because it will be available on the next update.

**Comment by YOSHIZAWAK** [comment]
Thank you for your reply. Please take actions on this matter.

**Comment by giacomofiorin** [comment]
Already did: check the status of the issue.

**Comment by YOSHIZAWAK** [comment]
Thank you for the speedy response.
