### ISSUE TITLE
Allow several instances of Colvars in VMD

### ISSUE THREAD

**Issue by jhenin** [Colvars/colvars#177]
Would help when looking at several molecules.

**Comment by giacomofiorin** [comment]
This was already considered in early stages of the VMD interface (7723b36) but is absolutely not trivial to implement.

If you allow returning control to the user after each `cv` command, problems will arise, for example between `cv frame` and `cv update`.  Please reopen with a list of changes to the scripting interface that will allow to safely switch between molecules, or to allow multiple instances of the module (both requiring changes that extend beyond the scope of one issue).
