### ISSUE TITLE
"cv save" doesn't work for ABF

### ISSUE THREAD

**Issue by fhh2626** [Colvars/colvars#186]
Dear Colvars developers,

Using "cv save", I can only get the metadynamics output file, but not ABF files. I guess this is because "cv save" calls write_output_files(), which is rewritten by colvarbias_meta class but not colvarbias_abf class. Could you have a look at this? 

Thanks,
Haohao

**Comment by giacomofiorin** [comment]
@jhenin You should take a first stab at this, unless there are some changes needed to the base class, in which case you can assign it back to me.

@fhh2626 Where are you running?  The ABF bias will write the PMF file every `colvarsRestartFrequency` on its own, so if you're running a MD simulation this is not a problem.

**Comment by jhenin** [comment]
This is now implemented by #188 .
