### ISSUE TITLE
Section 4.1.18 of the manual (Advanced usage of the rmsd component) outdated?

### ISSUE THREAD

**Issue by fabian-paul** [Colvars/colvars#207]
Section 4.1.18 of the manual mentions the option "translateReference" to disable automatic superposition of reference frames. However the only option that seems to works is "centerReference". Is the manual outdated or is this me mixing up two things?

**Comment by giacomofiorin** [comment]
Hi @fabian-paul you are right, this is a typo: thank you for pointing it out.  The updated manual should be online shortly.
