### ISSUE TITLE
Document wall constant scaling

### ISSUE THREAD

**Issue by jhenin** [Colvars/colvars#211]
In the transition period between the deprecated upper / lowerWallConstant keywords at the colvar level and those in the harmonicWall biases, we have the same keywords with different meanings in different contexts. In wall biases the force constants are scaled by the square width, whereas they at are unscaled in colvar context.

The risk I see is that users see that their legacy input is deprecated, and create new input by carrying over the values of parameters with the same name - that seems reasonable enough.

I think there should be stringent warnings about that in the documentation, in the deprecation message, and in sample inputs where relevant.

I'll create a change set to that effect.

**Comment by giacomofiorin** [comment]
I think that most people would either read the documentation of the new form and set it up accordingly, or ignore the deprecation warning and continue with the compatibility code.

This change set would be useful for the few not falling in the two examples above.  I am OK with it, but I think that one condition of the improved doc is that it isn't more confusing to first-time readers.

**Comment by jhenin** [comment]
Here. I tried to avoid adding confusion.
