### ISSUE TITLE
Better moving restraints when restarting

### ISSUE THREAD

**Issue by jhenin** [Colvars/colvars#221]
If the first timestep is not 0, staged moving restraints should compute the correct stage number.

In a related issue, is firsttimestep is provided to NAMD as a Tcl parameter, that is too late for CVM to take it into account when it gets initialized. It would be good to find a way to catch that (in cvm::update() ?).

**Comment by giacomofiorin** [comment]
This is tricky.  The state file already carries over the step number and
uses it to compute when stages should be changed.

How to ensure that the user-specified firstTimeStep will always be more
accurate than that?

**Comment by jhenin** [comment]
You're right. Let's forget I said anything.
