### ISSUE TITLE
Substrate Unbinding using PathCV and eABF

### ISSUE THREAD

**Issue by mrinal-shekhar** [Colvars/colvars#223]
Hello, 
I am trying to perform eABF using pathCV as collective variable to calculate the PMF of a substrate unbinding. Path is discretized in 12 equidistant discrete images with S(r)=0 (bound) to S(r)=1 (unbound). The way i define colvars is in the following way. 
  colvar {
   name                  s

   width                 0.01
   lowerboundary         0.00
   upperboundary         1.00

   scriptedFunction      pathCVs
   extendedLagrangian    on
   extendedFluctuation   0.01

	rmsd {
     	atoms {
       		atomNumbers {490174 490175 490176 490179 490180} # heavy atoms of the substrate

     }

refpositionsfile    ./setup/image.0.pdb #system pdb (protein+ligand)
componentExp	1}

   
	rmsd {
     	atoms {
       		atomNumbers {490174 490175 490176 490179 490180}

     }

refpositionsfile    ./setup/image.1.pdb
componentExp	2}

   
	rmsd {
     	atoms {
       		atomNumbers {490174 490175 490176 490179 490180}

     }

refpositionsfile    ./setup/image.2.pdb
componentExp	3}

   
	rmsd {
     	atoms {
       		atomNumbers {490174 490175 490176 490179 490180}

     }

refpositionsfile    ./setup/image.3.pdb
componentExp	4}

   
	rmsd {
     	atoms {
       		atomNumbers {490174 490175 490176 490179 490180}

     }

refpositionsfile    ./setup/image.4.pdb
componentExp	5}

   	rmsd {
     	atoms {
       		atomNumbers {490174 490175 490176 490179 490180}

     }

refpositionsfile    ./setup/image.5.pdb
componentExp	6}

  	rmsd {
     	atoms {
       		atomNumbers {490174 490175 490176 490179 490180}

     }

refpositionsfile    ./setup/image.6.pdb
componentExp	7}

   
	rmsd {
     	atoms {
       		atomNumbers {490174 490175 490176 490179 490180}

     }

refpositionsfile    ./setup/image.7.pdb
componentExp	8}

   
	rmsd {
     	atoms {
       		atomNumbers {490174 490175 490176 490179 490180}

     }

refpositionsfile    ./setup/image.8.pdb
componentExp	9}

   
	rmsd {
     	atoms {
       		atomNumbers {490174 490175 490176 490179 490180}

     }

refpositionsfile    ./setup/image.9.pdb
componentExp	10}

   
	rmsd {
     	atoms {
       		atomNumbers {490174 490175 490176 490179 490180}

     }

refpositionsfile    ./setup/image.10.pdb
componentExp	11}

   
	rmsd {
     	atoms {
          atomNumbers {490174 490175 490176 490179 490180}
     }

refpositionsfile    ./setup/image.11.pdb
componentExp	12}

}
#############################################################
# Distance from string
#############################################################

colvar {
   name                  z

   width                 0.01

   scriptedFunction      pathCVz

   
	rmsd {
     	atoms {
       		atomNumbers {490174 490175 490176 490179 490180}

     }

refpositionsfile    ./setup/image.0.pdb
componentExp	1}

   
	rmsd {
     	atoms {
       		atomNumbers {490174 490175 490176 490179 490180}

     }

refpositionsfile    ./setup/image.1.pdb
componentExp	2}

   
	rmsd {
     	atoms {
       		atomNumbers {490174 490175 490176 490179 490180}

     }

refpositionsfile    ./setup/image.2.pdb
componentExp	3}

   
	rmsd {
     	atoms {
       		atomNumbers {490174 490175 490176 490179 490180}

     }

refpositionsfile    ./setup/image.3.pdb
componentExp	4}

   
	rmsd {
     	atoms {
       		atomNumbers {490174 490175 490176 490179 490180} 

     }

refpositionsfile    ./setup/image.4.pdb
componentExp	5}

   	rmsd {
     	atoms {
       		atomNumbers {490174 490175 490176 490179 490180}

     }

refpositionsfile    ./setup/image.5.pdb
componentExp	6}

  	rmsd {
     	atoms {
       		atomNumbers {490174 490175 490176 490179 490180}

     }

refpositionsfile    ./setup/image.6.pdb
componentExp	7}

   
	rmsd {
     	atoms {
       		atomNumbers {490174 490175 490176 490179 490180}

     }

refpositionsfile    ./setup/image.7.pdb
componentExp	8}

   
	rmsd {
     	atoms {
       		atomNumbers {490174 490175 490176 490179 490180}

     }

refpositionsfile    ./setup/image.8.pdb
componentExp	9}

   
	rmsd {
     	atoms {
       		atomNumbers {490174 490175 490176 490179 490180}

     }

refpositionsfile    ./setup/image.9.pdb
componentExp	10}

   
	rmsd {
     	atoms {
       		atomNumbers {490174 490175 490176 490179 490180}

     }

refpositionsfile    ./setup/image.10.pdb
componentExp	11}

   
	rmsd {
     	atoms {
          atomNumbers {490174 490175 490176 490179 490180}
     }

refpositionsfile    ./setup/image.11.pdb
componentExp	12}

}

#############################################################
# ABF section
#############################################################
harmonicWalls {
   colvars s
   lowerWalls        0.00
   upperWalls        1.00
   lowerWallConstant  10.0
   upperWallConstant 10.0
}

harmonicWalls {
   colvars z
   lowerwalls        -0.5
   upperwalls         5.0
   #lowerWallConstant     1.0
   #upperWallConstant     1.0   

}

abf {

    colvars s
    fullSamples 1000
    CZARestimator yes
    writeCZARwindowFile yes
    
}

harmonic {
   colvars               z
   centers               0.0
   forceConstant         0.5
}

My issue is that the starting S(r) value even if i initiate simulation from any of the 12 images is around 0.5, which is weird. I am confused as to what i am doing wrong here?
Mrinal

**Comment by jhenin** [comment]
Hi Mrinal,

You could do a short test simulation without the abf bias, and without extendedLagrangian keywords, and check the colvars trajectory. To check that the RMSD values are what you expect, you can also add a couple variables, each containing one RMSD component, and no scripted function.

Side note: the componentExp lines are not necessary - but shouldn't change the results.

Best,
Jérôme

**Comment by giacomofiorin** [comment]
Hi @mrinal-shekhar were you able to figure out if the individual `rmsd` components give you reasonable numbers?

**Comment by mrinal-shekhar** [comment]
Hi @giacomofiorin,
I followed @jhenin`s comments and it seems that i am getting reasonable numbers. So what extra i had do was to align the protein based on the CA atoms for each image in the string and then calculate the rmsd based on the heavy atoms of the ligand. In other words, atoms involved in the rmsd calculation and the alignment were different. Here is a sample colvars file that i have made, please let me know if it sounds reasonable.

rmsd {
     	atoms {
        atomNumbers { 490174 490175 490176 490179 490180 } %ligand heavy atom
      centerReference yes 
        rotateReference yes
		refPositionsGroup {atomNumbers xx xxx xxxx 
}
refpositionsfile ./setup/image.0.pdb %protein pdb
}
refpositionsfile ./setup/image.0.cnst % Heavy atom of the ligand 
refPositionsCol B
refPositionsColValue 1

I am a little bit confused about centerReference Yes and rotateReference Yes
Mrinal

**Comment by jhenin** [comment]
Yes, that looks correct.
