### ISSUE TITLE
Feature request: providing a public method to access the scalar_com_gradient of an atom group

### ISSUE THREAD

**Issue by HanatoK** [Colvars/colvars#242]
I am working on a colvar constituted by any combination of current available colvar components. A problem is that I need to know the sub-CVCs gradients with respect to their atom groups when the sub-CVCs support explicit gradients, and that is stored in `scalar_com_gradient`. Currently it seems there is no public method to access it.
I think it's somewhat strange that the gradient of an `atom` is public while the gradient of an `atom_group` is not.

**Comment by jhenin** [comment]
I agree with you that there are inconsistencies in the visibility of different class members. In hindsight I would favor a more conservative style where more class data is private, unless otherwise necessary.

**Comment by giacomofiorin** [comment]
Keeping more data private (with optional public accessors) is definitely a generally good style: there are currently still many violations of it to be progressively phased out.

In the case of the gradients, @jhenin a while ago provided access to the atomic gradients to support alternative implementations of the total colvar forces (e.g. Eric Darve's). The visibility of the atomic gradients was needed for this.

Making the group's COM gradient is definitely reasonable along those lines.
