### ISSUE TITLE
Add subsection to briefly describe compiler options & unsupported features

### ISSUE THREAD

**Issue by giacomofiorin** [Colvars/colvars#250]
There are several components or software environment features that affect the functionality of Colvars and are not always determined by the hosting engine alone:
- Tcl interpreter
- Lepton library
- C++11 syntax

A subsection containing just a list of links to the specific features that depends upon them should be enough.

**Comment by jhenin** [comment]
I definitely agree. Just two comments:
- a certain fraction of users (hard to gauge, but a growing one) use precompiled binaries, and have no knowledge of the compilation environment. So far we've kept them informed by adapting each documentation to the default features found in precompiled binaries. This new documentation would be most useful to users who compile their stuff, making them aware of what they're missing and might be able to add to their build with extra some effort.
- the impact of this would be much less without the C++11 section. So far it would concern the geometric path variables, and I haven't yet given up hope of backporting those. Are there other features in the pipeline where C++11 will be unavoidable?

**Comment by giacomofiorin** [comment]
Because C++11 support depends on additional technical details, I put it as a webpage to be maintained separately (see #266), which should make the doc lighter indeed by just linking it.
