### ISSUE TITLE
How to compute the derivatives optimal rotation with respect to atomic coordinates in colvar component?

### ISSUE THREAD

**Issue by HanatoK** [Colvars/colvars#251]
I have rotated the atomic coordinates as following:
**X**' = **R**(**X**-**X**_c)
The colvar is defined as a scalar function of a set of rotated atomic coordinates:
y = f(**X**')
and its derivatives with respect to the rotated atomic coordinates (df/dx') are already know. The rotation quaternion is stored in a object with `cvm::rotation` type. Which member functions in `cvm::rotation` should I use to compute explicitly the derivatives of f with respect to the unrotated coordinates?

**Comment by jhenin** [comment]
The RMSD cvc is an example of this, and the way it handles the rotation is by setting `b_center` and `b_rotate` in the atom group, then letting it handle everything transparently.

If you really need the explicit derivatives, they are given by `cvm::rotation::dQ0_1` and `dQ0_2`, the derivatives of the leading eigenvector with respect to the fitting group (the reference) and the fitted group, respectively.

**Comment by HanatoK** [comment]
> The RMSD cvc is an example of this, and the way it handles the rotation is by setting `b_center` and `b_rotate` in the atom group, then letting it handle everything transparently.
> 
> If you really need the explicit derivatives, they are given by `cvm::rotation::dQ0_1` and `dQ0_2`, the derivatives of the leading eigenvector with respect to the fitting group (the reference) and the fitted group, respectively.

The RMSD uses the same set of atoms as group for fitting. Is it able to parse an atom group first and then specify another different set of atoms as fitting group for it manually? I have tried the following:
```
// parse a group of atoms for fitting
cvm::atom_group* tmp_fitting_atoms = parse_group(conf, "fittingAtoms");
tmp_fitting_atoms->b_center = true;
tmp_fitting_atoms->b_rotate = true;
tmp_fitting_atoms->b_user_defined_fit = true;
tmp_fitting_atoms->disable(f_ag_scalable);
tmp_fitting_atoms->disable(f_ag_scalable_com);
tmp_fitting_atoms->fit_gradients.assign(tmp_fitting_atoms->size(), cvm::atom_pos(0.0, 0.0, 0.0));
std::string reference_position_file_lookup = "refPositionFile" + cvm::to_str(i_frame + 1);
std::string reference_position_filename;
get_keyval(conf, reference_position_file_lookup.c_str(), reference_position_filename, std::string(""));
std::vector<cvm::atom_pos> reference_fitting_position(tmp_fitting_atoms->size());
cvm::load_coords(reference_position_filename.c_str(), &reference_fitting_position, tmp_fitting_atoms, reference_column, reference_column_value);
// setup the atom group for calculating
tmp_atoms->b_center = true;
tmp_atoms->b_rotate = true;
tmp_atoms->b_user_defined_fit = true;
tmp_atoms->disable(f_ag_scalable);
tmp_atoms->disable(f_ag_scalable_com);
tmp_atoms->fit_gradients.assign(tmp_fitting_atoms->size(), cvm::atom_pos(0.0, 0.0, 0.0));
tmp_atoms->ref_pos = reference_fitting_position;
tmp_atoms->center_ref_pos();
tmp_atoms->enable(f_ag_fit_gradients);
tmp_atoms->enable(f_ag_fitting_group);
tmp_atoms->fitting_group = tmp_fitting_atoms;
tmp_atoms->rot.request_group1_gradients(tmp_fitting_atoms->size());
tmp_atoms->rot.request_group2_gradients(tmp_fitting_atoms->size());
reference_fitting_frames.push_back(reference_fitting_position);
comp_atoms.push_back(tmp_atoms);
```
but the code crashed.

**Comment by jhenin** [comment]
This looks like the right general idea. You are just trying to reproduce the behavior of a standard atom group with the user options rotateReference, centerReference and fittingGroup. Can you do it that way first to have a reference behavior that hopefully should do what you want?

Can you collect more info about the crash? A backtrace with debug info enabled may be enough to see what's wrong here.

**Comment by HanatoK** [comment]
@jhenin Thanks for your reply! I find the crashes happened because I also enabled the `b_rotate`, `b_user_defined_fit` and similar options for the reference groups. These options should be only used for the atom groups that needed fitting.
Solution:
```
//tmp_fitting_atoms->b_center = true;
//tmp_fitting_atoms->b_rotate = true;
//tmp_fitting_atoms->b_user_defined_fit = true;
```
