### ISSUE TITLE
Strange boundary effect in extended-Lagrangian based simulation

### ISSUE THREAD

**Issue by fhh2626** [Colvars/colvars#252]
Hi, all,

Recently, when I ran a eABF (or its variants) simulation using stratification strategy, the free energies close to window boundaries look quite weird:
![Figure_1](https://user-images.githubusercontent.com/25058290/56710208-902a0780-6757-11e9-88ca-7279146474d0.png)
(The PMF describing the hydration of methane is calculated using the files of NAMD ABF turorial. I only changed ABF to eABF)

Sometimes the little noise are not very significant (for example, in the deca-alanine case), but the problem should exist whatever the system is.
The CZAR, UI and naive estimator give similar results, so this should not be a issue of estimator.
I'm not should if this problem exists in an old version of Colvars, but it seems this is the first time I got the problem.

Thanks,
Haohao

**Comment by jhenin** [comment]
Thank you for the report @fhh2626 and sorry about the delay in replying.

Do the artefacts also appear in the PMFs for individual windows? How did you merge them?

You may be aware of this already: getting a PMF from stratified eABF is a little special because the free energy estimators depend on histograms, and the histograms cannot be simply merged. Instead the gradients should be obtained for each window separately, then merged, then integrated.

**Comment by fhh2626** [comment]
Thanks for your reply @jhenin .

What you said just implies that one cannot use "InputPrefix" to merge czar files, even with "writeCZARwindowFile". Am I correct? If so, then there is no way to use pABF with stratification strategy. Is it possible to have pABF in abf_integrate?

Thanks,
Haohao

**Comment by jhenin** [comment]
> there is no way to use pABF with stratification strategy

You can use pABF in each window. Once you gather the window together, the CZAR scheme is essentially broken, because there is no continuous histogram. I suppose one could cheat and rescale the different zcount files to join them, WHAM-style.

> Is it possible to have pABF in abf_integrate?

I'm not sure what you mean.

**Comment by fhh2626** [comment]
Thanks for your explanation. Now, if one wants to use pABF, an explicit call of NAMD must be made, which means one cannot integrate a gradient file easily using only grad and count file. It would be, if possible, very good to have something like abf_integrate, but using a pABF-like integrator.

**Comment by jhenin** [comment]
Let me add something on the vocabulary here - maybe we need to improve the documentation on this.

pABF is a variant of ABF dynamics where the biasing force is obtained by differentiating a PMF, which is obtained by numerical integration of the gradient estimate. This requires rapid integration, which is implemented in 2D and 3D using a Poisson solver.

Even when using regular ABF or eABF (not pABF) the Poisson solver is convenient to obtain a reliable, deterministic estimate of the integrated PMF. That is, I think, what you are referring to.

Now if you have a stratified eABF calculation in dimension > 1, then integrating the PMF gets complicated. You'd need to concatenate the CZAR gradients, then integrate the result directly.

I think you could obtain this result by renaming the <prefix>.czar.grad files to just <prefix>.grad and running a zero-step ABF with those. Then the PMF file would actually be a CZAR result.

**Comment by fhh2626** [comment]
Thanks for your explanation @jhenin . Now it's very clear for me.
Yes, when running simulation without a stratification strategy, everything is OK.

According to the discussion, I suggest to improve the documentation about "writeCZARwindowFile". Now it says: These separate ﬁle is only useful when joining adjacent windows from a stratiﬁed eABF simulation, either to continue the simulation in a broader window or to compute a CZAR estimate of the PMF over the full range of the coordinate(s). 
I think either this sentence or the option should be removed (please tell me if I misunderstood something).

Thanks again.
Haohao

**Comment by jhenin** [comment]
Very good point! I added this option after a user request (from Chris, I think) but I didn't think fully about the consequences. As it is, it is an incomplete solution to a non-trivial problem.

**Comment by fhh2626** [comment]
> For my peace of mind, can you please confirm that these artefacts are not present in PMFs from individual windows? Thanks.

@jhenin I ran a simulation characterizing the ethanol solvation and see the issue again. This time I merged the czar.grad file directly (without using inputPrefix). Maybe this is a issue of boundary restraints?

**Comment by jhenin** [comment]
@fhh2626 Thanks. Does changing the type of boundary restraint with your patch fix the wrong results you had on ethanol solvation?

**Comment by fhh2626** [comment]
@jhenin I tested it today. Sadly, no. I suggest to expand the boundary a little bit when collecting data for the CZAR estimator. As for merging windows, combining directly the gradients is probably the safest way.
