### ISSUE TITLE
Dependencies between same-level objects

### ISSUE THREAD

**Issue by jhenin** [Colvars/colvars#254]
The need arises because of e.g. #249 .

**Comment by giacomofiorin** [comment]
Replying to last message in issue #249. 

Indeed, I was thinking to start with having the same requirements between "siblings", with the idea of making it more flexible as needed (like you propose).

I'll be happy to help with at least part of it when my schedule clears up a bit in a few weeks.

**Comment by giacomofiorin** [comment]
Long term this is important to reuse pieces of computation for efficiency purposes. I do not have an immediate use case to prioritize this, but it needs to be done anyway. Whether to keep the GitHub issue or keep it open is almost cosmetic.

**Comment by giacomofiorin** [comment]
As before, closed or open is just cosmetics :-)
