### ISSUE TITLE
integration issues with abf_integrate

### ISSUE THREAD

**Issue by mrinal-shekhar** [Colvars/colvars#256]
Hello,
So i have trying to perform a 2D meta-eABF using path collective variable as reaction coordinate. To generate the PMF i use abf_integrate, however the PMF generated looks non ideal. Furthermore, looking at the output of abf_integrate the intial gradient RMS is 137535.7, which i feel is huge, i never get the gradient RMS below 500. Here is the output which i see with default settings

Number of variables: 2
min = 2 width = 0.1 n = 270 PBC: no
min = 0 width = 0.01 n = 30 PBC: no
Opening file drr.abf.count for reading

Using metadynamics-style sampling with hill height: 0.01
Varying hill height by factor 0.5
Sampling until convergence at temperature 500

Setting minimum number of steps to 32400000

Initial gradient RMS is 13735.7
Step 1000000 ; gradient RMSD is 13735 ; relative change per 1M steps -4.91793e-05
Step 2000000 ; gradient RMSD is 13734.5 ; relative change per 1M steps -3.77781e-05
Step 3000000 ; gradient RMSD is 13734 ; relative change per 1M steps -3.51791e-05
Step 4000000 ; gradient RMSD is 13733.5 ; relative change per 1M steps -3.56911e-05
Step 5000000 ; gradient RMSD is 13733.1 ; relative change per 1M steps -3.46372e-05
Step 6000000 ; gradient RMSD is 13732.6 ; relative change per 1M steps -3.55138e-05
Step 7000000 ; gradient RMSD is 13732.1 ; relative change per 1M steps -3.46151e-05
Step 8000000 ; gradient RMSD is 13731.6 ; relative change per 1M steps -3.78615e-05
Step 9000000 ; gradient RMSD is 13731.1 ; relative change per 1M steps -3.92754e-05
Step 10000000 ; gradient RMSD is 13730.5 ; relative change per 1M steps -3.95554e-05
Step 11000000 ; gradient RMSD is 13729.9 ; relative change per 1M steps -4.27534e-05
Step 12000000 ; gradient RMSD is 13729.3 ; relative change per 1M steps -4.57096e-05
Step 13000000 ; gradient RMSD is 13728.7 ; relative change per 1M steps -4.61053e-05
Step 14000000 ; gradient RMSD is 13728 ; relative change per 1M steps -4.76892e-05
Step 15000000 ; gradient RMSD is 13727.3 ; relative change per 1M steps -4.93842e-05
Step 16000000 ; gradient RMSD is 13726.6 ; relative change per 1M steps -5.13597e-05
Step 17000000 ; gradient RMSD is 13725.9 ; relative change per 1M steps -5.2e-05 - changing hill height to 0.005
Step 18000000 ; gradient RMSD is 13725.5 ; relative change per 1M steps -2.63983e-05 - changing hill height to 0.0025
Step 19000000 ; gradient RMSD is 13725.4 ; relative change per 1M steps -1.29975e-05 - changing hill height to 0.00125
Step 20000000 ; gradient RMSD is 13725.3 ; relative change per 1M steps -6.43456e-06 - changing hill height to 0.000625
Step 21000000 ; gradient RMSD is 13725.2 ; relative change per 1M steps -3.16898e-06 - changing hill height to 0.0003125
Step 22000000 ; gradient RMSD is 13725.2 ; relative change per 1M steps -1.65236e-06
Step 23000000 ; gradient RMSD is 13725.2 ; relative change per 1M steps -1.57398e-06
Step 24000000 ; gradient RMSD is 13725.2 ; relative change per 1M steps -1.62955e-06
Step 25000000 ; gradient RMSD is 13725.1 ; relative change per 1M steps -1.63352e-06
Step 26000000 ; gradient RMSD is 13725.1 ; relative change per 1M steps -1.63827e-06
Step 27000000 ; gradient RMSD is 13725.1 ; relative change per 1M steps -1.6326e-06
Step 28000000 ; gradient RMSD is 13725.1 ; relative change per 1M steps -1.60174e-06
Step 29000000 ; gradient RMSD is 13725.1 ; relative change per 1M steps -1.61792e-06
Step 30000000 ; gradient RMSD is 13725 ; relative change per 1M steps -1.63616e-06
Step 31000000 ; gradient RMSD is 13725 ; relative change per 1M steps -1.61278e-06
Step 32000000 ; gradient RMSD is 13725 ; relative change per 1M steps -1.6484e-06
Step 33000000 ; gradient RMSD is 13725 ; relative change per 1M steps -1.63875e-06
Run 49670932 total iterations; acceptance ratio is 0.664372 ; final gradient RMSD is 13725
Writing PMF to file drr.abf.grad.pmf
Writing sampling histogram to file drr.abf.grad.histo
Writing estimated FE gradient to file drr.abf.grad.est
Writing FE gradient deviation to file drr.abf.grad.dev

I also played around with a few parameters 
abf_integrate drr.abf.grad -n 1000000000 -h 0.5 -t 600
Opening file drr.abf.grad for reading
Number of variables: 2
min = 2 width = 0.1 n = 270 PBC: no
min = 0 width = 0.01 n = 30 PBC: no
Opening file drr.abf.count for reading

Using metadynamics-style sampling with hill height: 0.5
Varying hill height by factor 0.5
Sampling 1000000000 steps at temperature 600

Initial gradient RMS is 13735.7
Step 100000000 ; gradient RMSD is 551.194 ; relative change per 1M steps -0.00959871
Step 200000000 ; gradient RMSD is 544.569 ; relative change per 1M steps -0.000120203
Step 300000000 ; gradient RMSD is 553.718 ; relative change per 1M steps 0.000168008
Step 400000000 ; gradient RMSD is 556.061 ; relative change per 1M steps 4.23261e-05
Step 500000000 ; gradient RMSD is 546.049 ; relative change per 1M steps -0.000180066
Step 600000000 ; gradient RMSD is 551.189 ; relative change per 1M steps 9.41426e-05 - changing hill height to 0.25
Step 700000000 ; gradient RMSD is 585.385 ; relative change per 1M steps 0.000620408 - changing hill height to 0.125
Step 800000000 ; gradient RMSD is 606.499 ; relative change per 1M steps 0.000360673 - changing hill height to 0.0625
Step 900000000 ; gradient RMSD is 631.804 ; relative change per 1M steps 0.00041724 - changing hill height to 0.03125
Step 1000000000 ; gradient RMSD is 643.021 ; relative change per 1M steps 0.000177533 - changing hill height to 0.015625
Run 1374237294 total iterations; acceptance ratio is 0.727676 ; final gradient RMSD is 643.021
Writing PMF to file drr.abf.grad.pmf
Writing sampling histogram to file drr.abf.grad.histo
Writing estimated FE gradient to file drr.abf.grad.est
Writing FE gradient deviation to file drr.abf.grad.dev

I am attaching the grad and the count files
Please help
Mrinal 

[count-grad-file.zip](https://github.com/Colvars/colvars/files/3144773/count-grad-file.zip)

**Comment by HanatoK** [comment]
I think this is because your sampling (drr.abf.count) is not ergodic or homogeneous. How long did your simulation last?

**Comment by jhenin** [comment]
Likely not a software issue.
