### ISSUE TITLE
Changes to improve integration of DEER code

### ISSUE THREAD

**Issue by giacomofiorin** [Colvars/colvars#269]
The aspects that touch on general code organization are becoming more relevant, so I'm opening an issue to not restrict the conversation to just myself and @fabsugar.  The `rad` bias and `deer` components require lots of "vertical" communication, e.g. between the bias and components.  The following are changes that I thing are needed or at least very desirable:

- [ ] Use the `f_cv_single_component` feature more transparently e.g. by having an accessor (`single_component()`?) that returns the `colvar::cvcs[0]` pointer after checking that the feature is enabled.  This arrangement is akin to `colvar::dist2()` and `f_cv_homogeneous`, which exists already.
- [ ] Provide accessors so that `cvc` member functions that biases can call them.  In the case at hand, `update_params_rad()` and `update_params_rad_chis()` are ad-hoc wrappers which could be better handled by a general method.  
- [ ] Use `cvc` internal fields to set default values for the parent `colvar` object. I already to have components set values like `lowerBoundary` (e.g. `rmsd` setting it to 0). @fabsugar pointed out that for `deer`- and `deerKernel`-based variables the default `width` of 1 makes no sense, and would like to have the `cvc` supply it.  The conditions under which this can be done are already captured by `f_cv_homogeneous` unless I am mistaken.

**Comment by fabsugar** [comment]
Thanks Giacomo,
about the second point I am already modifying update_params_rad() and update_params_rad_chis() in order to have a more general method. The target to have local functions that provide derivatives with respect to the parameters and a global one that use those values to optimize them.

**Comment by fabsugar** [comment]
points 1 and 3 should be done, 2 is underway
