### ISSUE TITLE
CV dashboard installation in VMD

### ISSUE THREAD

**Issue by BIORAK** [Colvars/colvars#270]
Hi,
  
   I was unable to figure out how to install CV dashboard in VMD. Can you suggest how do it ?

**Comment by giacomofiorin** [comment]
Hi @BIORAK you can start from `README.md` in `vmd/cv_dashboard`.  However, do keep in mind that some of the features in the current Dashboard version (Tcl code) require features in the underlying Colvars module (C++ code).  So VMD would have to be recompiled.

Luckily, new VMD alpha builds have just been released:
https://www.ks.uiuc.edu/Development/Download/download.cgi?PackageName=VMD

Closing this for now, please comment if specific steps do not work as documented.

**Comment by jhenin** [comment]
@BIORAK To be specific: the new alpha builds come with the dashboard included, so you don't need to install anything specific. Just look for it under Extensions.

Note that unfortunately the Colvars functionality is not yet available in the official Windows builds of VMD. We are working to change that.

**Comment by giacomofiorin** [comment]
Well, to be more specific, we *were* working (and also successful) on having Colvars built on Windows.  Currently, what we are doing is simply waiting for the official UIUC Windows build to be released.

You are very welcome to send an email to `vmd@ks.uiuc.edu` (the VMD developers' address, not the mailing list) if you need a Windows build.
