### ISSUE TITLE
Compilation with Lepton on Windows with Intel compiler

### ISSUE THREAD

**Issue by RayMaterialsDesign** [Colvars/colvars#281]
Hi Colvars Developers and Users,

I was trying to build the COLVARS library in LAMMPS/lib/colvars and met with these errors on Windows 7:
 
lepton/src/ParsedExpression.cpp(326): error: a function declared "dllimport" may not be defined
  ostream& Lepton::operator<<(ostream& out, const ExpressionTreeNode& node) {
                   ^

lepton/src/ParsedExpression.cpp(348): error: a function declared "dllimport" may not be defined
  ostream& Lepton::operator<<(ostream& out, const ParsedExpression& exp) {
                   ^

compilation aborted for lepton/src/ParsedExpression.cpp (code 2)
make: *** [Makefile.md:105: lepton/src/ParsedExpression.obj] Error 2
 
I am using: Intel(R) C++ Intel(R) 64 Compiler for applications running on Intel(R) 64, Version 17.0.4.210 Build 20170411.

Could you please point me to the right direction?

Thanks,
Ray

**Comment by giacomofiorin** [comment]
Hi Ray, sorry for the late reply (traveling).  Lepton is a dependency for Colvars, and it is very useful to define custom functions but not a hard dependency.  For example, we do not have Lepton compiled in when Colvars is bundled with VMD currently.  You could probably remove the corresponding targets and the `-DLEPTON` flag, and the compilation should go fine.

The Lepton library, written and maintained by @peastman is bundled with OpenMM.  On Windows, OpenMM is compiled with Visual Studio and I don't know whether Intel is officially supported there (especially for older Windows builds).

I may also be missing something in how Lepton is bundled with LAMMPS to support compilation with Visual Studio.

**Comment by peastman** [comment]
No idea what that error message means.  It works fine compiling with Visual Studio.  The Intel compiler must be doing something differently, but I don't know what.

**Comment by giacomofiorin** [comment]
@RayMaterialsDesign I changed the title since this is an issue with compiling Lepton on your particular combination of compiler/platform.  There is currently no option to enable/disable Lepton with a single flag, because it is otherwise fairly portable.

If you are still trying to address these, here are more details regarding what I suggested earlier.

For the `make`-based build, you should remove the `lepton` directory and `Makefile.deps` and modify the `Makefile.common` of Colvars as follows:

```
diff --git a/lib/colvars/Makefile.common b/lib/colvars/Makefile.common
index 595876507..405bb8935 100644
--- a/lib/colvars/Makefile.common
+++ b/lib/colvars/Makefile.common
@@ -57,20 +57,20 @@ LEPTON_OBJS = \
        lepton/src/ParsedExpression.o lepton/src/ExpressionProgram.o    \
        lepton/src/Operation.o lepton/src/Parser.o
 
-COLVARS_OBJS = $(COLVARS_SRCS:.cpp=.o) $(LEPTON_OBJS)
+COLVARS_OBJS = $(COLVARS_SRCS:.cpp=.o)
 
 %.o: %.cpp
-       $(CXX) $(CXXFLAGS) $(COLVARS_INCFLAGS) -Ilepton/include -DLEPTON -c -o $@ $<
+       $(CXX) $(CXXFLAGS) $(COLVARS_INCFLAGS) -c -o $@ $<
 
 $(COLVARS_LIB):        Makefile.deps $(COLVARS_OBJS)
-       $(AR) $(ARFLAGS) $(COLVARS_LIB) $(COLVARS_OBJS) $(LEPTON_OBJS)
+       $(AR) $(ARFLAGS) $(COLVARS_LIB) $(COLVARS_OBJS)
 
 
 Makefile.deps: $(COLVARS_SRCS)
        @echo > $@
        @for src in $^ ; do \
          obj=`basename $$src .cpp`.o ; \
-         $(CXX) -MM $(COLVARS_INCFLAGS)  -Ilepton/include -DLEPTON \
+         $(CXX) -MM $(COLVARS_INCFLAGS) \
            -MT '$$(COLVARS_OBJ_DIR)'$$obj $$src >> $@ ; \
          done
```

For the Cmake-based build, you should remove the `lepton` folder as well and modify the Cmake recipe file as follows:
```diff --git a/cmake/CMakeLists.txt b/cmake/CMakeLists.txt
index 91fb930be..c13659620 100644
--- a/cmake/CMakeLists.txt
+++ b/cmake/CMakeLists.txt
@@ -427,7 +427,6 @@ foreach(SIMPLE_LIB POEMS USER-ATC USER-AWPMD USER-COLVARS USER-H5MD
     elseif(PKG_LIB STREQUAL h5md)
       target_include_directories(h5md PUBLIC ${LAMMPS_LIB_SOURCE_DIR}/h5md/include ${HDF5_INCLUDE_DIRS})
     elseif(PKG_LIB STREQUAL colvars)
-      target_compile_options(colvars PRIVATE -DLEPTON)
       target_include_directories(colvars PRIVATE ${LAMMPS_LIB_SOURCE_DIR}/colvars/lepton/include)
       target_include_directories(colvars PUBLIC ${LAMMPS_LIB_SOURCE_DIR}/colvars)
     else()
```

**Comment by RayMaterialsDesign** [comment]
Hi Giacomo,

Thank you so much for your replies.  I haven’t got around to test it but I really appreciate your help.

Best regards,
Ray

**Comment by giacomofiorin** [comment]
@RayMaterialsDesign I submitted the following PR to the LAMMPS repository, which among other things allows to disable Lepton with conventional make by automating what I posted earlier.
https://github.com/lammps/lammps/pull/1724
Should you need a flag for CMake as well, please comment here.

**Comment by RayMaterialsDesign** [comment]
Hi Giacomo,

I finally got around to revisit compiling COLVARS for Windows with IntelMPI.  What you have suggested below worked well and I was able to build LAMMPS with USER-COLVARS.

Thanks,
Ray

**Comment by giacomofiorin** [comment]
Great!  The latest LAMMPS version now has that option implemented both for traditional make and Cmake.
