### ISSUE TITLE
Compile on Blue Gene Q using mpixlcxx_r

### ISSUE THREAD

**Issue by ketankhare** [colvars/colvars#31]
Dear Developers,

I am using a Makefile on a Blue Gene Q machine with the following settings for CXX and CXXFLAGS:
CXX =		/bgsys/drivers/ppcfloor/comm/xl.ndebug/bin/mpixlcxx_r
CXXFLAGS =	-g -O3 -qarch=qp -qtune=qp -qsmp=omp -qstrict

Such a makefile works well for the colvars library distributed with LAMMPS version dated 30Oct14.  However, the compiler issues an error if I use these settings with the corresponding libraries distributed with LAMMPS versions dated 9Dec14 (latest stable) and 16Feb15 (developers).  The error is as follows: 

"colvartypes.h", line 327.5: 1540-1113 (S) The class template name "matrix2d" must be followed by a < in this context."

All of the these libraries are compiled successfully by the GNU compiler on the same system.  Could you please advise on possible resolutions for this error?

I appreciate your help!
Thanks,
Ketan

**Comment by akohlmey** [comment]
Please try either the latest LAMMPS-ICMS version or download the latest colvars snapshot from github and update your LAMMPS version with it. This issue should have been already corrected only the code has not yet been included into the upstream LAMMPS version (in fact, i emailed a patch to upgrade colvars in LAMMPS with the latest changes to steve earlier today).

**Comment by ketankhare** [comment]
Thanks Axel!  Your legendary promptness never fails to impress.  Cheers!
