### ISSUE TITLE
Parser detects component name keyword inside unrelated customFunction line

### ISSUE THREAD

**Issue by jhenin** [Colvars/colvars#311]
The following config:
```
colvar {
    name d
    customFunction distance + 2

    distance {
        name distance
        group1 {
            atomNumbers 1 2
        }
        group2 {
            atomNumbers 3 4
        }
    }
}
```

gives the error:
```
colvars: Error: definition for atom group "group1" not found.
colvars: Error: definition for atom group "group2" not found.
colvars: Error: keyword "+" is not supported, or not recognized in this context.
colvars: Error: in setting up component "distance".
colvars: Error: no valid components were provided for this collective variable.
```

Expected behavior: the distance keyword should only be parsed when at the beginning of a line.

**Comment by giacomofiorin** [comment]
See the PR for the code fix.  A quick workaround is to use braces, which would probably be also good practice when using long Lepton expressions.
```
colvar {
    name d
    customFunction { distance + 2 }

    distance {
        ...
    }
}
```

**Comment by jhenin** [comment]
Thanks. Another fun example of what can be done with current master:
```
colvar {
    distance {
        group1 {
            atomNumbers 1 2
        }
        group2 {
            atomNumbers 3 4
        }
    } BLAH BLAH BLAH name myColvar
}
```
The parser accepts this as valid, which is a nice trick to insert comments.

Looking at the patch now...

**Comment by jhenin** [comment]
@giacomofiorin  I'm considering creating a "minor bug" label for this and the other minor parser issue.

**Comment by giacomofiorin** [comment]
Fine with me.  This is definitely not a thing that should scare people off with a red label :-)
