### ISSUE TITLE
Documentation of script-based vs C++11 path CVs

### ISSUE THREAD

**Issue by giacomofiorin** [Colvars/colvars#315]
Should the documentation of the script-based path CVs:
https://colvars.github.io/colvars-refman-namd/colvars-refman-namd.html#sec:pathcv
be merged with that of the full geometric implementation?
https://colvars.github.io/colvars-refman-namd/colvars-refman-namd.html#sec:cvc_gpath

There are currently pros and cons for using either, but it would definitely help to see them discussed close to each other.

**Comment by HanatoK** [comment]
Actually the algorithm of pathCV.tcl should be similar to what I did in the arithmetic path in CV space (https://colvars.github.io/colvars-refman-namd/colvars-refman-namd.html#sec:cvc_apathCV), but pathCV.tcl uses RMSD of selected atoms with respect to those in reference frames while apathCV uses RMSD of user-defined CVs with respected to CV values on a path.
This paper (https://pubs.acs.org/doi/10.1021/acs.jctc.8b00563) mentioned both cases.
