### ISSUE TITLE
vmd cv_dashboard: display_marker fails bc of typo

### ISSUE THREAD

**Issue by ReneHamburger1993** [Colvars/colvars#318]
vmd [cv_dashboard_plots.tcl](https://github.com/Colvars/colvars/blob/bd1fb9d56bc12443abe965a7277e7ea458bd17f7/vmd/cv_dashboard/cv_dashboard_plots.tcl#L259) fails because of typo in Line259+280 `set canv "[set ${ns}::w].f.cf"` instead of `set canv "[set ${ns}::w].cf"`

**Comment by jhenin** [comment]
Thanks for the report @ReneHamburger1993 ! What version of VMD / Multiplot is this? I have not seen this with the versions I have tested.

**Comment by ReneHamburger1993** [comment]
I tested it with VMD 1.9.3 release; and VMD1.9.4a37 and a38 and just discovered that I used multiplot 2.0 from vmdICE which was overriding the plugin dir version multiplot 1.7
It works fine with multiplot package version 1.7
Cheers
René

**Comment by jhenin** [comment]
Interesting, those people have made a Viennese fork of Multiplot. Despite the higher version number, it seems outdated now, the official 1.7 has a lot of extra changes.

Thanks for the report nonetheless. I hope you enjoy the Dashboard: please keep testing and reporting anything that seems out of line.
