### ISSUE TITLE
combine ABF strata in LAMMPS

### ISSUE THREAD

**Issue by kfattah** [colvars/colvars#32]
I have a question regarding the stratification in ABF using colvars. Based on what I read in papers, I'm thinking of divide my simulation transition coordinate into N non-overlapping windows to enhance the performance of the sampling. After doing independent simulations in each stratum (windows) I need to combine the result to recover the full PMF along the transition coordinate, the "COLLECTIVE VARIABLES MODULE
Reference manual for LAMMPS" says:

"If the colvar space has been partitioned into sections (windows) in which independent ABF simulations have been run, the resulting data can be merged using the the input keyword of the fix ID group-ID colvars command."

So I was wondering if it means that I should pass 'output01.pmf', 'output01.pmf', ...,'outputN.pmf' files to get a combined PMF results?!

Because what I understand from 'fix colvars' manual is that the input option is to specify a state file in order to continue the simulation. So I don't know how it can be used to combine the results.

I would really appreciate it if you can clarify that for me.

Cheers,
Kasra.

**Comment by giacomofiorin** [comment]
This seems to be an issue with the LAMMPS version of the manual, this work is done by the inputPrefix keyword, which is internal to the ABF algorithm.  I changed it and uploaded the new text.
