### ISSUE TITLE
[Gromacs Integration] cmake error: Cannot specify sources for target "libgromacs" 

### ISSUE THREAD

**Issue by flblanc** [Colvars/colvars#323]
Dear developers,

I am trying to patch the current Gromacs 2020 version with colvars, but I am confused as to how to proceed. So far I have:
- Downloaded and extracted the sources of Gromacs 2020 from [https://ftp.gromacs.org/pub/gromacs/](url)
- Downloaded and extracted the gromacs-compatible branch of _colvars_ from @HubLot github
- Run `sh update-colvars-code.sh -f /path/to/gromacs-2020/src` ; I am then instructed to build with `cmake`
- Created a `build` sub-repertory in the `gromacs-2020` repertory and run `cmake -DGMX_BUILD_OWN_FFTW=ON ..` from there. 

The following errors are encountered when `cmake` runs: 
`CMake Error at src/gromacs/fileio/CMakeLists.txt:37 (target_sources):
  Cannot specify sources for target "libgromacs" which is not built by this
  project.
`

`
CMake Error at src/gromacs/selection/CMakeLists.txt:39 (target_sources):
  Cannot specify sources for target "libgromacs" which is not built by this
  project.
`

Note that the Gromacs `cmake` and subsequent compilation work fine when I do not attempt to patch it with _colvars_.

I assume this is because I either have forgotten a step in the procedure or am trying to use incompatible versions of the codes, but I honestly don't have a clue. Could you please help me? 

Thanks in advance.

**Comment by giacomofiorin** [comment]
Hi @flblanc The version for the GROMACS files currently included in #190 is relative to an earlier version of the GROMACS tree.  The CMake recipe (along with other files) have been edited recently upstream, and I got the same error using the most recent GROMACS snapshot (GitHub mirror https://github.com/gromacs/gromacs).

Get in touch with @HubLot and @jhenin to find out what version of GROMACS to compile with.

If you have other questions feel free to comment on #190 to keep the information on that branch together until it's merged.

**Comment by HubLot** [comment]
Hi @flblanc :)

Indeed, the cmake files are currently matched to the develop version of Gromacs.

I'm gonna create a copy of these file to match the Gromacs 2020 sources. I'll keep you posted.

**Comment by HubLot** [comment]
Hi @flblanc,

I pushed a new commit on the gromacs branch with a patch for Gromacs 2020.
It should work now.

**Comment by flblanc** [comment]
Hi @HubLot , been a while :D 
I confirm I could compile gromacs 2020 with the patch. Thank you !
