### ISSUE TITLE
Analyzing plumed with VMD Dashboard

### ISSUE THREAD

**Issue by spant18** [Colvars/colvars#326]
I am trying to analyze a gromacs trajectory with VMD dashboard but getting errors like:

colvars: # colvarsTrajFrequency = 0 [default]
colvars: # colvarsRestartFrequency = 0 [default]
colvars: # scriptedColvarForces = off [default]
colvars: # scriptingAfterBiases = off [default]
colvars: Warning: no collective variables defined.
colvars: Collective variables initialized, 0 in total.
colvars: No collective variables biases were defined.
colvars: Error: keyword "wholemolecules" is not supported, or not recognized in this context.

Even if i comment out "wholemolecules" it give me errors on CVs. Please find attached plumed file.

**Comment by giacomofiorin** [comment]
Shouldn't you be using the PLUMED VMD plugin instead?

**Comment by spant18** [comment]
But Dashboard does give an option to load gromacs COLVARS (which i assume is PLUMED) files. I think its easier to capture a particular conformation using Dashboard than PLUMED VMD plugin.

**Comment by giacomofiorin** [comment]
@spant18 That option refers to the GROMACS interface for Colvars:
https://github.com/Colvars/colvars/pull/190
and not PLUMED.  

The Dashboard (a GUI interface to the Colvars module written entirely in Tcl/Tk) uses a large set of Tcl commands to access the internals of the Colvars module.  This arrangement requires the module to be linked against VMD (either statically or dynamically).  But PLUMED is currently used in VMD only as a command-line tool (i.e. an external code to VMD altogether).  Dynamic linking could be an option to link PLUMED into VMD as a plugin, but it will definitely take some work by the PLUMED developers in making this feasible on most VMD builds.

Why don't you open an issue for this on the PLUMED repository?  @jhenin or I can comment if needed.

**Comment by spant18** [comment]
Understood. Yes, i have just posted a question on PLUMED google groups.
