### ISSUE TITLE
Adding atoms on the fly in NAMD requires one timestep delay

### ISSUE THREAD

**Issue by jhenin** [colvars/colvars#33]
When a config loaded after NAMD startup requires new atoms, the data only becomes available one timestep later. Trying to access it on the same timestep triggers a this error:
FATAL ERROR: GlobalMasterServer::callClients() did not find all requested atoms

The solution to that is to implement a one-timestep delay before coordinates are accessed and the colvar can be computed - and biases that use it, as well.

A workaround until then is to request those atoms preemptively at an earlier stage.

**Comment by giacomofiorin** [comment]
This could be fixed more easily by adding support to the redesigned colvarproxy_namd class.

**Comment by jhenin** [comment]
Indeed, fixed.
