### ISSUE TITLE
Molecule view reset when loading coordinates in VMD

### ISSUE THREAD

**Issue by jhenin** [Colvars/colvars#336]
When creating a colvar that requires reading a PDB file, some background operation (possibly the creation of a temporary molecule) cause the camera viewpoint to be reset. It would be nice to avoid this side effect if possible.

**Comment by giacomofiorin** [comment]
This is the line where the VMD PDB file reader is invoked (original commit 23f8480151ecc4efb03c9172e0804456d509d6ce):
```
  int tmpmolid = vmd->molecule_load(-1, pdb_filename, "pdb", tmpspec);
```
A VMD `Molecule` instance is needed to get the various fields, but it should be possible to call directly the molfile function, since the format is assumed to be `"pdb"` anyway.

**Comment by giacomofiorin** [comment]
From a quick look at the implementation of `molecule_load()` there are a few plugin functions to be called.  If you choose to just back up the VMD view with Tcl in the Dashboard (useful for other purposes, too), please keep the issue open. I wouldn't mind removing the need to create a temporary molecule altogether and use the molfile reader directly.

**Comment by jhenin** [comment]
>  If you choose to just back up the VMD view with Tcl in the Dashboard

Done, keeping the issue open.

**Comment by giacomofiorin** [comment]
Done. Completed!
