### ISSUE TITLE
New implementation (dipoleAngle component)

### ISSUE THREAD

**Issue by alejob** [colvars/colvars#34]
Hello, first of all thank you for this great module, Colvars, it has been very useful for our lab. I write to you because I'm implementing a "new" collectible variable (on Colvar source code), "dipoleAngle". This new collective variable is very similar to "angle", but measure/orients the dipole angle of a molecule. This implementation works for harmonic bias and metadynamics, but (still) not for ABF with  "hideJacobian true" option , because I don't know how to calculate the "inverse gradient" and the "Jacobian derivative" of my new colvar. I've read the Colvar paper, some cites of this paper and the tutorial-abf.pdf but I still don't figure out how to calcute it.

If you can help me with this I'll be very greatful and I'll be able to make a pull request.

I leave you a link to the new collective variable development http://dlab.cl/wp-content/uploads/2015/03/development_colvar.pdf

Thanks

**Comment by giacomofiorin** [comment]
Hello Alejandro, thank you for contributing a new variable! 

In principle you do not need to have inverse gradients and jacobian, as you noted.  However ABF or any other method based on system forces you will need these regardless of hidejacobian, but there are several variables like that. 

You can just not define inverse gradients and jacobian, as in those variables, and the code will prevent from using ABF with them. 

To implement inverse gradients and jacobian as analytical functions, check out our references, particularly the 2010 jctc paper, and papers by Ciccotti or Den Otter cited in there. 

Jerome will probably follow up with a summary of good strategies to derive an inverse gradient field suitable for this.

**Comment by alejob** [comment]
Hello Giacomo, thanks for your help!, I'll read the papers that you suggest. 

Meanwhile, I'll finish my new implementation without inverse gradients and jacobian, and maybe in a new pull I'll be able to implement it.

**Comment by jhenin** [comment]
Hi Alejandro, thanks for your contribution. The inverse gradient is fairly simple: one option that always works is to divide the gradient by its square norm, to satisfy the conditions outlined in our papers.

You can get a Jacobian term that will be correct in all but some twisted multidimensional ABF cases the following way: imagine you set the potential energy to zero, so that atoms are non-interacting, and hence uniformly distributed in space. What is then the probability distribution of your variable? That gives you the average Jacobian determinant. In your case, my guess would be that it's probably proportional to sin(theta), because the orientation of the dipole vector would be uniformly distributed. If that is indeed sin(theta), then the term you want is d(ln(sin(theta))/dtheta, which is cotan(theta).

**Comment by alejob** [comment]
Hi Jérôme, thanks for your help. It seems very simple to implement inverse gradient and Jacobian determinant in the way you show, and actually, it is equal to collect. variable "angle". I'll check this results and I'll pull it in a second request (to avoid errors).

**Comment by alejob** [comment]
Hi, I'm almost ready with this enhancement. I'm developing this for NAMD, and to create a dipole I needed to extract charges from the .psf, I did this modifying the colvarproxy_namd.* file.

Now I'm trying to do this (extract charges) with LAMMPS colvarproxy file, but I have some problems. My question is: is it possible to make a merge without the modifications to colvarproxy_lammps.* file?, in this way this new implementation will not be available for a while for LAMMPS.

**Comment by alejob** [comment]
Any suggestion to do this (extract charges from LAMMPS) would  be great too.

**Comment by giacomofiorin** [comment]
Hello Alejandro, if you see in colvarproxy.h (base class header) there are several functions that are not implemented (i.e. they are only stubs).  You should implement those functions as such in the base header, and only reimplement them for colvarproxy_namd where you know how to get the charges.

Axel has sure suggestions about how to get them in LAMMPS though.

**Comment by akohlmey** [comment]
to extract atomic charges in LAMMPS, you can follow more-or-less the code path that is used to read masses and just add them as additional entry to the commdata struct and so on. however, LAMMPS is very flexible with respect to  what per-atom information is stored and how. with masses, you can have per-atomtype masses (atom->mass) or per-atom masses (atom->rmass) which is available is indicated by atom->rmass_flag. charges are optional, you you need to test for atom->q_flag or else assign 0.0. a further complication is that atoms may also have point dipoles and/or variable charges.

but don't worry too much, this should be a simple change, and if you have a working code for NAMD, i can easily add the equivalent code for LAMMPS myself with the necessary safeguards. i am currently traveling to conduct a workshop, so it may take a little longer until i can look into it properly, in case there are any problems.

**Comment by alejob** [comment]
Hi, I've tried to do that Axel (follow the mass implementation), but it was a little messy to me in LAMMPS. If you can do that change to the LAMMPS proxy would be excelent. For the moment  I'll follow the Giacomo's suggestion.

If I understand you Giacomo, I should move all my code from colvarcomp_angle.cpp (where I developed this new collective variable) to colvarproxy_namd.cpp and in colvarproxy.h just set my functions to 0 (like the already implemented stubs functions). am I right?

**Comment by giacomofiorin** [comment]
Yes, but don't move there all the code you wrote, just the new member functions of the colvarproxy_namd or colvarproxy.h classes.

I recommend also that you check out the "proxy" branch: I'm doing a bit of reorganization of the class in there, and LAMMPS and VMD aren't finished yet, but the revised colvarproxy_namd class is in a working state.

**Comment by alejob** [comment]
Hi guys, I finally could read charges from LAMMPS, modifying colvarproxy_lammps.cpp and fixcolvars.cpp (thanks to the "q_flag" Axel's tip).

 I think that is a good option to make two pull request, one for the colvarproxy* implementation and an other one to the full enhacement. This is to avoid breaking the colvarproxy code in case of error (to make all the possible colvarproxy code corrections before upload all the enhancement). What do you think?

**Comment by giacomofiorin** [comment]
If dipoleAngle requires the charges to work, there is probably little use in separating the two contributions.

I would recommend that we first pull from your repository into a new branch of this repository, then I conclude the changes I was working on in the "proxy" branch, and we then merge the two.

**Comment by alejob** [comment]
Excelent, I'll create a new branch (dipole_angle) and I'll pull to the Colvars repository.

**Comment by alejob** [comment]
Hi Giacomo, to which branch can I make the pull request (proxy, histogram, cvc-off)?, or will you create a new one?

**Comment by giacomofiorin** [comment]
I would recommend proxy.

On Thu, Apr 30, 2015 at 1:37 PM, Alejandro Bernardin <
notifications@github.com> wrote:

> Hi Giacomo, to which branch can I make the pull request (proxy, histogram,
> cvc-off)?, or will you create a new one?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/colvars/colvars/issues/34#issuecomment-97892257>.
>



-- 
Giacomo Fiorin
Assistant Professor of Research
Institute for Computational Molecular Science (ICMS)
College of Science and Technology, Temple University
1925 North 12th Street (035-07), Room 704D
Philadelphia, PA 19122-1801
Phone: +1-215-204-4213
https://icms.cst.temple.edu/members.html
http://giacomofiorin.github.io/
