### ISSUE TITLE
Error running metadynamics "dumpFreeEnergyFile" is not supported

### ISSUE THREAD

**Issue by daipayans** [Colvars/colvars#359]
Hi Colvars team, 
While performing metadynamics, I am getting the following error message:
**colvars: Error: keyword "dumpfreeenergyfile" is not supported, or not recognized in this context.**

Has this keyword been modified to writeFreeEnergyFile (default: on) and keepFreeEnergyFiles (default: off). Should I replace dumpFreeEnergyFile with both writeFreeEnergyFile and keepFreeEnergyFiles set to on?

Following is my current colvar configuration file:

```
colvarsTrajFrequency 5000
colvarsRestartFrequency 5000

colvar {
    name rc1
    width 0.1
    lowerBoundary 0.0
    upperBoundary 4.0

    rmsd {
        atoms {
            atomNumbers {<list of atomID>}   # not including the list here.
        }
        refPositionsFile reference.pdb
    }
}

metadynamics {
    name meta_rc1
    colvars rc1
    hillWeight 0.1              # Default is 0.01 - higher numbers = faster
    newHillFrequency 1000       # Default is 100 - lower numbers = faster
    wellTempered on
    biasTemperature 1500
    dumpFreeEnergyFile yes
    writeHillsTrajectory on
    hillwidth 1.0
}

harmonicWalls {
    name wall_rc1
    colvars rc1
    lowerWalls 0.0
    upperWalls 4.0
    lowerWallConstant 1.0
    upperWallConstant 1.0
}
```

**Comment by giacomofiorin** [comment]
Hi @daipayans, `dumpFreeEnergyFile` has been deprecated (and not documented) since 2013! May I ask what is your source for it?

`writeFreeEnergyFile` (just that, no additional keywords needed) is the keyword for writing the PMF.

https://colvars.github.io/colvars-refman-namd/colvars-refman-namd.html#sec:colvarbias_meta_output

**Comment by daipayans** [comment]
Hi @giacomofiorin, Thanks for your response. I had started a simulation with writeFreeEnergyFile and that is working fine. The source of the error were from two sources (in my case): 
1) NAMD tutorial for using metadynamics (see Pg. 4 in https://www.ks.uiuc.edu/Training/Tutorials/namd/metadynamics-tutorial/meta-tutorial.pdf). I feel this should be updated by the author of the tutorial.
2) The second link is from a third party, so I would expect users to read the documentation related to the software and tutorials. (http://www.ub.edu/cbdd/?q=content/brief-intro-metadynamics-namd)

**Comment by giacomofiorin** [comment]
@daipayans Can you email Zhaleh and let her know?

I can also add an example input for metadynamics in the manual suitable for copying/pasting, which is the only part of the tutorial that most people use anyway.

**Comment by daipayans** [comment]
@giacomofiorin sure I will do that and copy you in the email.
