### ISSUE TITLE
Amend/move the "non-trivial example"?

### ISSUE THREAD

**Issue by giacomofiorin** [Colvars/colvars#362]
The example configuration in `fig:colvars_diagram` and related configuration is becoming a bit out of place, because: (1)  compared to a decade ago, few people use a difference of two distances as a reaction coordinate, and (2) most of the section that this example is located in now talks about other stuff than just colvars and biases.

Maybe it can be moved to the previous section, i.e. the "crash course", as a more advanced example following the first one? Possibly, it could be simplified or updated, as well. 

I do recall talking with one PI years ago and realizing that they (genderless: not plural) had misunderstood that you *must* build a colvar out of multiple components, because there is no suitable function in Colvars... I do remember the same PI also admitting to not reading the articles that they had just listed in a (well-cited) review article that they published. But given how the field has evolved I would be inclined to throw a bone to their trainees, given the pressure they're under.

**Comment by jhenin** [comment]
I fully agree with this. I'm not even sure the figure is needed anymore, maybe a good config example would be more helpful.

**Comment by giacomofiorin** [comment]
Applied this change to the branch of #361
