### ISSUE TITLE
ouput traj file limited to 100 lines

### ISSUE THREAD

**Issue by ludjam** [Colvars/colvars#364]
I am doing a simple SMD simulation with the following config file :

colvar {
	name z_SMD
	distanceZ {
		main { atomNumbersRange 2464-2510 }
		ref { dummyAtom (0,0,36) }
		axis (0,0,1)
		}
	}	
	
harmonic {
	name SMD1
	colvars z_SMD
	forceConstant 10
	centers 0 
	targetCenters -29
	targetNumSteps 15000
	outputCenters true
	outputAccumulatedWork true
}

But the output file is no longer than 100 lines thus finishing at step 9800 instead of 15000. I fill a bit limited with that. I am using lammps 16 march 2018 version because is the one accessible for me on the slurm cluster that I use. 
Is this problem avoided with more recent versions or is there any way to overpass this limitation ?

Many thanks.

**Comment by ludjam** [comment]
And adding the line "colvarsTrajFrequency 150" at the beggining of my config file give me an empty output traj file... 
Therefore I cannot even reduce the sampling frequency of the output so that the entire trajectory fill the limit of 100 lines.

**Comment by giacomofiorin** [comment]
@ludjam Did the simulation finish all 15000 steps, or did you get a restart file written?

If the simulation terminates before it gets to either point, there may still be data left in the buffer (memory) before it is fully written to disk.  For the number of columns that you are printing, the byte count of 100 lines is almost exactly 10 kB of data: could this be the size of the buffer in the filesystem that you are using?

If you want data to be fully written to disk more often, you can either save a state file with LAMMPS or use `colvarsRestartFrequency` to save just a Colvars state file. Either one is okay.

Can you please confirm that it works? We won't fix the version in the 2018 LAMMPS, but I am interested to find out if there is a bug around.

**Comment by ludjam** [comment]
I do think the simulation ended as lammps log and dump files ended at step 15000 and a restart file is written.
A empty colvars.state file is also created...

The problem is indeed solved (colvars.traj end at step 1500) by setting "colvarsRestartFrequency 98" so that a colvars.state file is created everytime a line is added to the colvars.traj.

**Comment by giacomofiorin** [comment]
@ludjam This is a bit confusing, because the numbers are inconsistent.  The first column of the colvars.traj file is the step number, not the line number, so the last line it should contain the 15000 step number (your last simulation step), not 1500.  Conversely, for 15000 steps and `colvarsRestartFrequency` equal to 100 (the default) you should get 151 lines of data (plus the header lines prefixed by `#`, which you should have noticed.

To clarify, can you confirm that you see the following messages in the log file?
```
colvars: Synchronizing (emptying the buffer of) trajectory file "xxxx.colvars.traj".
colvars: Saving collective variables state to "xxxx.colvars.state".
```
