### ISSUE TITLE
hideJacobian appears off by a factor of 2 for distance CV

### ISSUE THREAD

**Issue by jeffcomer** [Colvars/colvars#367]
I haven't used hideJacobian for a long time (since I was in France, I think), but for some reason I decided to use it yesterday. I got very strange results. I've done some tests with a neon–neon system. For comparison, I've anchored all the PMFs so that the plateau at long distances is 1. Here's what I found:

![plot_colvars_hideJacobian](https://user-images.githubusercontent.com/7032880/95899151-bed5dc80-0d55-11eb-8580-5b27d687f3ed.png)

If I ~~subtract~~ add the geometric contribution 2 kT ln(r) from the PMF resulting from running NAMD without hideJacobian, I get good agreement with the Lennard-Jones potential. However, with hideJacobian on, NAMD 2.14, 2.13, and 2.12 give a PMF that looks to be overcorrected (~~subtracting~~ adding 4 kT ln(r)). I have to go back to NAMD 2.11 to get the right answer.

I tried to trace back where the problem is coming from. I think it's this line in colvarcomp_distances.cpp:
`void colvar::distance::calc_Jacobian_derivative()
{
  jd.real_value = x.real_value ? (2.0 / x.real_value) : 0.0;
}`

I think the 2.0 should just be 1.0. As far as I can tell, this value is isn't used elsewhere, but I was a little hesitant to change it, because I thought that maybe it could break something else.

**Comment by jhenin** [comment]
Thanks a lot for the report @jeffcomer ! The expression for the Jacobian derivative of the distance was correct, but there was a bug in the way this is accounted for in the reported total force.

**Comment by giacomofiorin** [comment]
I agree with removing the `hideJacobian` option. Those who really want it can probably subtract the term from the PMFs on their own. 

Ok to remove it right away then, without deprecating it first, since it has been buggy for some time anyway?

**Comment by jhenin** [comment]
Yes, removal seems like an option. Before that though, I'd like the opinion of @jeffcomer  - after all, he did try it recently. Jeff?

**Comment by giacomofiorin** [comment]
Yes. My question was implicitly addressed to both.

**Comment by jeffcomer** [comment]
Sorry for disappearing for a few days.

My suggestion might be to keep the hideJacobian feature. It is quite common for radial PMFs to be plotted with the geometric contribution hidden, so it is likely to be a useful feature for some. Back when I was struggling to understand geometric contributions to the PMF, it was nice to be able to use it as a reference implementation to ensure that my own implementation of subtracting the Jacobian term was correct.

I'm currently working on some tutorials that make use of hideJacobian (which is how I ran into this problem) and compare to literature where it has been removed. I explain the geometric contribution in the tutorial (similar to Giacomo's explanation on the mailing list), but it's nice to have an implementation that is guaranteed to be correct, rather than have to explain to the students exactly how to implement it.

But if you'd think it be easier just to remove it, I couldn't fault you.

Is hideJacobian supported only for a few colvars? I think it is likely to be useful only for Distance colvars and maybe DistanceXY colvars. Would disabling it for other colvars make it easier to support from your point of view?

**Comment by giacomofiorin** [comment]
`hideJacobian` is currently supported for all variables that have inverse gradients implemented, e.g. also `angle`, `dihedral`, `rmsd`. It could be disabled for those with a little bit of work.

I do agree that it is easier to do the subtraction automatically, rather than explaining students how to subtract it. But that only applies to ABF or in any case PMFs computed using inverse gradients. It does not apply to umbrella sampling or metadynamics, at which point you would also need to explain why their PMFs are different.

My suggestion above was to document in the manual itself what the Jacobian term means, in a way that is a bit more accessible to readers without going through the entire formulation of inverse gradients (as is done now). This is a general issue, more suitable for a manual section and less suitable for a self-contained specialized tutorial. The tutorial could of course link the manual section.

Do you want to perhaps contribute what you are writing about the Jacobian to the manual itself?

**Comment by giacomofiorin** [comment]
Also, please @jhenin correct me if I am wrong but with both CZAR and Zheng/Yang the Jacobian cannot be computed analytically. I believe that recommending to use `hideJacobian` would make comparisons difficult with eABF, as well.

**Comment by jhenin** [comment]
@giacomofiorin That is correct, hideJacobian is strictly limited to classic ABF with projection of total atomic forces.

One side "benefit" of hideJacobian, which is completely unique and not really documented in any literature, is that the Jacobian force is compensated for systematically, at the colvar level, without the need for sampling anything or projecting any total force. So in principle it could function in the absence of an ABF bias (I think it does really). It's a form of very cheap enhanced sampling method, that could do non-trivial work in the case of RMSD where the Jacobian forces are very high.

**Comment by jhenin** [comment]
At present this option is not really recommended by any documentation. In the absence of a strong reason for removal, I say we keep the status quo until new elements arise.

**Comment by giacomofiorin** [comment]
You mean maintaining the hideJacobian option, which is okay, but how about
documenting the bug and explaining what the term is, independently of the
method used?

**Comment by jhenin** [comment]
I'll give a shot at improving the documentation.

**Comment by giacomofiorin** [comment]
I can do, too. Just needed to agree on moving content from the ABF section
to a more general place.

**Comment by jhenin** [comment]
I've committed a first improvement on the hideJacobian documentation. It references the TI equation, which itself can move to a different section. I think hideJacobian itself still belongs in the ABF section.

**Comment by giacomofiorin** [comment]
Yes.
