### ISSUE TITLE
Is gspath supported on back-ends without PDB parsers?

### ISSUE THREAD

**Issue by jhenin** [Colvars/colvars#372]
I suppose it isn't, and then that should be reflected in the documentation. See e.g. #371

**Comment by jhenin** [comment]
What do you think @HanatoK ?

**Comment by giacomofiorin** [comment]
That was going to be indeed my next question, too. Since XYZ files are allowed they would probably work, but the examples to use PDB files. It may be a good idea to use XYZ throughout, for portability and also because it is parsed in double precision, i.e. far more precise than the PDB.

**Comment by HanatoK** [comment]
@jhenin In the `gspath` implementation I use the `cvm::load_coords` to load the reference position files, and `cvm::load_coords` will return an error saying that PDB column cannot be specified with the XYZ format. The initialization of `gspath` indeed requires specifying a PDB column to mark the reference atoms, so I suppose `gspath` does not support XYZ.
Frankly speaking, I do not know too much about the XYZ format, especially about how to specifying atoms for the moving frame of reference. I would take a look at the current document to see if there are examples.

**Comment by giacomofiorin** [comment]
@HanatoK How `load_coords()` reads coordinate files is explained in the documentation of `refPositionsFile`:
https://colvars.github.io/colvars-refman-namd/colvars-refman-namd.html#atom-group|refPositionsFile
and is specifically one the following cases (quoting from the doc):
_(i) the file contains exactly as many records as the atoms in the group: all positions are read in sequence;
(ii) (most common case) the file contains coordinates for the entire system: only the positions corresponding to the numeric indices of the atom group are read;
(iii) if the file is a PDB file and refPositionsCol is specified, positions are read according to the value of the column refPositionsCol (which may be the same as atomsCol)._

Cases (i) and (ii) may be XYZ files as well, which contain nothing but coordinates. Only if you specify the (optional) PDB column letter code, then the file must be a PDB. In the regtests for the path variables, it seems to me that you are using (ii), so you could just as easily use XYZ files.

**Comment by giacomofiorin** [comment]
One thing that comes to mind about this, is that those three alternative modes could perhaps be explained in the section about the PDB format, and referred to when introducing `atomsFile`, `refPositionsFile`, etc.

**Comment by HanatoK** [comment]
@jhenin @giacomofiorin
I tried the XYZ format and it seems that `gpath` just occasionally support it. I take a look at the code and remember that I swiped and the similar code from `rmsd` and did not throw an error when the reference column string is empty, so the parser falls back to XYZ and the code works.
What do I need to do with this issue? A new test?

**Comment by jhenin** [comment]
@HanatoK Since it works as advertised in the current documentation, I think there is nothing more to do for this.

**Comment by giacomofiorin** [comment]
Hey, since this issue was closed, to avoid forgetting I did the doc change that I volunteered for in 03034b3c

Please take a look that it checks out and is clear enough.
