### ISSUE TITLE
Deprecate enableForces?

### ISSUE THREAD

**Issue by giacomofiorin** [Colvars/colvars#376]
The feature is a holdover from many years ago, and is arguably no longer useful (see the dependency resolution system) or appropriate (see the errors when neglecting forces on `fittingGroup` atoms, which would now be more visible with greater sampling and for this reason `enableFitGradients` is on by default).

Any objections to deprecating it now (i.e. undocumenting) and discontinuing it later?

**Comment by jhenin** [comment]
I agree. I am unsure what people might be using this for, but the best way to know is a scream test.

**Comment by giacomofiorin** [comment]
Done. Note that the actual scream test will be when the feature is actually removed from the code, in addition of not being documented.
