### ISSUE TITLE
Linking error

### ISSUE THREAD

**Issue by athomps** [colvars/colvars#39]
When I like COLVARS with LAMMPS I get the following undefined symbols:

colvarbias_alb::colvarbias_alb(std::string const&, char const*)'
colvarbias_restraint_harmonic::colvarbias_restraint_harmonic(std::string const&, char const*)'
colvarbias_restraint_linear::colvarbias_restraint_linear(std::string const&, char const*)'
colvarmodule::quaternion::from_simple_string(std
colvarmodule::quaternion::position_derivative_inner(colvarmodule
colvarmodule::quaternion::to_simple_string() const'
colvarmodule::rotation::calc_optimal_rotation(std
colvarmodule::rotation::crossing_threshold'
colvarmodule::rotation::monitor_crossings'
colvarmodule::rvector::from_simple_string(std
colvarmodule::rvector::to_simple_string() const'
operator>>(std::istream&, colvarmodule::quaternion&)'
operator>>(std::istream&, colvarmodule::rvector&)'
operator<<(std::ostream&, colvarmodule::quaternion const&)'
operator<<(std::ostream&, colvarmodule::rvector const&)'

e.g.

mpicxx -O3 -L../../lib/colvars ......  -lcolvars ....

Undefined symbols for architecture x86_64:
   "colvarmodule::quaternion::from_simple_string(std::basic_string<char,
std::char_traits<char>, std::allocator<char> > const&)", referenced from:
       colvarvalue::from_simple_string(std::basic_string<char,
std::char_traits<char>, std::allocator<char> > const&) in
libcolvars.a(colvarvalue.o)

**Comment by akohlmey** [comment]
aidan,

which platform/CPU is this on? it looks like MacOSX with x86_64, but it is hard to guess...
also, have you tried to update the code in LAMMPS with the github code, which has a few additional bugfixes?

i have tried since you emailed steve and me a few things and checked with both gcc and clang on linux (fedora 21, x86_64) and didn't have any problems.

axel.

**Comment by athomps** [comment]
Both Mac OSX (gcc 4.9) and Sandia's big linux cluster (icc 15.0).

--
      Aidan P. Thompson
      01444 Multiscale Science
      Sandia National Laboratories
      PO Box 5800, MS 1322      Phone: 505-844-9702
      Albuquerque, NM 87185     Fax  : 505-845-7442
      E-mail:athomps@sandia.gov Cell : 505-218-1011

**Comment by athomps** [comment]
Behavior not affected by adding or removing other LAMMPS packages.

--
      Aidan P. Thompson
      01444 Multiscale Science
      Sandia National Laboratories
      PO Box 5800, MS 1322      Phone: 505-844-9702
      Albuquerque, NM 87185     Fax  : 505-845-7442
      E-mail:athomps@sandia.gov Cell : 505-218-1011

**Comment by athomps** [comment]
Problem solved. I neglected to update the LAMMPS lib/colvars/Makefile from github. Sorry for the confusion.
