### ISSUE TITLE
Wrong sign in gradient of unit vector values?

### ISSUE THREAD

**Issue by jhenin** [Colvars/colvars#395]
It seems this derivative is invariant by swapping v1 and v2, because the sine is computed as always positive.
https://github.com/Colvars/colvars/blob/45d57c80dd43be620d699927d123ddbc4786c001/src/colvarvalue.cpp#L583

**Comment by jhenin** [comment]
You're right, the sign cancels out. Actually the *sine* cancels out as well, and the expression simplifies a bunch.

I'm going to merge the PR with the unit test nonetheless, because I loved being able to try the simplified expression and test it instantly.

**Comment by giacomofiorin** [comment]
:-) I assume you have checked that the result is the same.
