### ISSUE TITLE
upper/lower_boundary feature blocking histogram with specific grid params

### ISSUE THREAD

**Issue by jhenin** [Colvars/colvars#403]
With histogramGrid, a histogram can in principle be defined on a colvar without defined boundaries. However this fails with the message `User-controlled feature "upper_boundary" cannot be enabled automatically`.
The histogram bias should be able to enable it. Maybe making the boundary features dynamic will suffice, however I need to check this for unwanted side effects.

**Comment by jhenin** [comment]
Coming back to this, I think the root of the issue is the feature "f_cv_grid". Since the grids live in different objects, not in the colvar itself, I think it makes things more complicated to have this as a feature of a colvar. @giacomofiorin Does a colvar need to know that it's being projected on a grid?

**Comment by giacomofiorin** [comment]
In my view `f_cv_grid` is needed only to check whether the colvar *can* be binned on a grid, but the colvar indeed doesn't need to know what its value is used for. I'm fine with letting the biases simply check that the colvar can be binned, but not actually change its internal member data.

The only thing that I would like to keep is the width and boundaries defaulting to the values currently set in the colvar. Although not set by the user, thanks to the changes in https://github.com/Colvars/colvars/pull/310 they are actually now better informed by the CVCs' functionality.
