### ISSUE TITLE
Support of Gromacs 2021

### ISSUE THREAD

**Issue by fhh2626** [Colvars/colvars#410]
Hi, @jhenin @giacomofiorin @HubLot ,

Just a question: is there any plan to support Gromacs 2021?

Best,
Haohao

**Comment by HubLot** [comment]
Hi @fhh2626,

Yes, we plan to support GROMACS 2021. I'm currently working on it and I hope we will release a patch soon!

Cheers,
Hubert

**Comment by fhh2626** [comment]
> Hi @fhh2626,
> 
> Yes, we plan to support GROMACS 2021. I'm currently working on it and I hope we will release a patch soon!
> 
> Cheers,
> Hubert

Thank you very much for your information!
