### ISSUE TITLE
design question: ACCESS problem of groups in distance vs distance_pairs like colvars

### ISSUE THREAD

**Issue by ReneHamburger1993** [Colvars/colvars#414]
Hi,
I am trying to implement a colvar myself similar to a distance one but which needs access to all positions of atoms inside group2.

I ran into the issue that for distance like colvars the atoms groups group1,group2 allow to access the center_of_mass of them via `group1->center_of_mass()` but the size of the group objects themselves are 0 when accessed by `group1->size()` after definition and inside the `calc_value()` functions. This is the case at least for `distance` and `distance_z` variables while its NOT the case for the `distance_pairs` components.

Why is it like that and how do I access e.g. `group1` atoms coords then?

**Comment by giacomofiorin** [comment]
Hi René, I presume you are using NAMD? Computation of centers of mass is done in parallel using internal functions of NAMD, but you can temporarily disable that using `scalable off`.
https://colvars.github.io/colvars-refman-namd/colvars-refman-namd.html#sec:cvc_common
If you're writing your own class and inheriting from one of the `colvar::distance*` classes, the constructor of that base class with issue:
```
  enable(f_cvc_com_based);
```
What you want is to either skip the inheritance from the distance variables, or at the very least use `disable(f_cvc_com_based)` in your class's constructor to override the base-class behavior.

**Comment by ReneHamburger1993** [comment]
Hi Giacomo,
yep I am using NAMD.
Nice, thanks for the quick reply!

Just found out that this is one of the subtle differences between `distance` and `distancePairs` and got it working! :)

René
