### ISSUE TITLE
Identical branches defect reported by coverity scan

### ISSUE THREAD

**Issue by akohlmey** [Colvars/colvars#416]
https://github.com/Colvars/colvars/blob/5304dd9bc2311b31897a83f2477c954e385c299e/src/colvarcomp_volmaps.cpp#L105

This line could be replaced by

```
int flags = colvarproxy::volmap_flag_gradients;
```
unless there should be two different variables on the two sides of the colon.

**Comment by giacomofiorin** [comment]
Thanks! Copy and paste mistake, as you probably guessed. The branch won't get executed at all in LAMMPS (initialization of the class will fail without the volumetric map backend). But the distinction will matter e.g. in VMD.

Closing it now and then sending a PR to LAMMPS to silence it.
