### ISSUE TITLE
Unchecked loop bound issue reported by coverity scan

### ISSUE THREAD

**Issue by akohlmey** [Colvars/colvars#417]
https://github.com/Colvars/colvars/blob/5304dd9bc2311b31897a83f2477c954e385c299e/src/colvargrid.cpp#L168

After reading `nd`, it should be checked if it has a reasonable value so that subsequent implicit memory allocations won't overflow, unless it can be guaranteed that it is reasonable (i.e. the file is not defective or edited).

**Comment by giacomofiorin** [comment]
Thanks, sounds good. There are indeed a couple of edge cases where folks can input their own file (e.g. [ensemble-biased metadynamics](https://colvars.github.io/colvars-refman-lammps/colvars-refman-lammps.html#sec:colvarbias_ebmeta)).

I set the limit to 50, which for a grid of just 2 points in each dimension equals 8 PB of memory. Safe to say that this is not going to be met very soon...
