### ISSUE TITLE
COLVARS_VERSION empty in update-colvars-code

### ISSUE THREAD

**Issue by HubLot** [Colvars/colvars#427]
Hi,

I just spot a bug when trying to patch a GROMACS root directory with the new `GMX_VERSION_STRING_OF_FORK` feature (see #423)
When launching `update-colvars-code.sh` outside its colvars directory, the variable `COLVARS_VERSION` is empty. The variable is correctly initialized when launching the script inside the colvars directory:
```bash
#COLVARS_VERSION empty
[santuz@aa]$ /path/to/colvars/update-colvars-code.sh gromacs-2020.6
#COLVARS_VERSION=2021-10-13
[santuz@aa]$ ./update-colvars-code.sh path/to/root/gromacs-2020.6
```

It's due to the function `get_colvarmodule_version` from  the file `version_functions.sh` (some others function will have the same behavior) which have relative paths and assume they are called from the colvars root directory.

**Comment by giacomofiorin** [comment]
@HubLot Not necessarily the relative path, but the fact that the version is being detected through Git command.  I just downloaded a Zip file, and confirm the issue you see.  (With a Git worktree, it works fine).
