### ISSUE TITLE
Doubt about constant in angle::calc_gradients

### ISSUE THREAD

**Issue by alejob** [colvars/colvars#43]
Hello, 
           I was checking the colvar::angle::calc_gradients() function and I have a doubt about a constant that I can't figure out why is there. In the next lines, 

```
dxdr1 = (180.0/PI) * dxdcos *
    (1.0/r21l) * ( r23/r23l + (-1.0) * cos_theta * r21/r21l );

dxdr3 = (180.0/PI) * dxdcos *
    (1.0/r23l) * ( r21/r21l + (-1.0) * cos_theta * r23/r23l );
```

there is a constant (180.0/PI) that doesn't appears in the gradient of angle. I know that constant is used to transform from radians to degree (like in line 68 in that same file), but in this case that's not necessary, because we need the expression in radians to calculate the force. Maybe there is another part of the code that needs that constant?.

I'm checking this because I need to know about that constant for the dipole_angle implementation that I developed in the proxy branch.

Cheers!

**Comment by jhenin** [comment]
Hi Alejandro,

> we need the expression in radians to calculate the force.

 The gradient unit is degree per Angstrom, consistent with our units that have degrees everywhere (and the forces are in kcal/mol/degree).

Best,
Jerome

**Comment by alejob** [comment]
Hi Jerome,
                 very clear explanation, thanks!
