### ISSUE TITLE
Some problems in Multidimensional histograms

### ISSUE THREAD

**Issue by fhh2626** [Colvars/colvars#431]
Hi,

I have some problems when using multidimensional histograms feature.

1. This feature may cause crash of the simulation when writing dat/dx files (Using latest gitlab version of NAMD patched with the latest version of Colvars). Attached are the files that can be used to reproduce this problem.
[test.zip](https://github.com/Colvars/colvars/files/7511279/test.zip)

2. Setting "outputFileDX" to none or an empty string cannot avoid writing a .dx file, instead, a file named "none" is generated.

3. In user's manual, 
`Keyword weights ⟨Treat vector variables as multiple observations of a scalar variable?⟩`.
I suspect the brief introduction is wrong.

Any help would be greatly appreciated,

Haohao

**Comment by jhenin** [comment]
Thank you @fhh2626 for your report. I'm quite busy, but this is very much at the front of my mind.

**Comment by giacomofiorin** [comment]
Hi @fhh2626 thanks for pointing these out, the third was a copy-paste error that I just fixed:
https://github.com/Colvars/colvars/commit/f215f1098c7315233df4b1abb328e42ae7c68066

The first two affect code last changed changed by @jhenin, so I'll wait until he has a chance to look at them.

**Comment by fhh2626** [comment]
Thanks for your reply @jhenin @giacomofiorin . I will be waiting for your news.

**Comment by jhenin** [comment]
Hi @fhh2626, I ran the input you provided and could not observe either of the errors you mention. Can you please send the standard output log of a faulty run?

**Comment by fhh2626** [comment]
> Hi @fhh2626, I ran the input you provided and could not observe either of the errors you mention. Can you please send the standard output log of a faulty run?
> 
> This reminds me of that issue: #337 but as far as I know it was solved completely by @giacomofiorin .

@jhenin You are absolutely right!!! I looked at my log file again and realized that I did an unlucky patch of NAMD. After a repatch using the latest version of Colvars, there is no problem. Sorry for the waste of your time. Please, forgive my stupid mistake.

Thanks again,
Haohao

**Comment by giacomofiorin** [comment]
Well, you did catch an error in the doc :-)

**Comment by jhenin** [comment]
Oh, good news :-)  Don't worry @fhh2626 , I'd rather have people report bugs when they see them, even if there can be an occasional mistake.
