### ISSUE TITLE
Update documentation/nodes for C++11 and Lepton + VMD

### ISSUE THREAD

**Issue by giacomofiorin** [Colvars/colvars#440]
I recently was able to build fully-functional VMD builds (i.e. including all the features available in the official LINUXAMD64 alpha builds available [here](https://www.ks.uiuc.edu/Development/Download/download.cgi?PackageName=VMD)) on RedHat/CentOS/Rocky Linux  versions 7 and 8. Ubuntu coming, although less of a priority since we don't/can't use it where I work.

The main enhancements are changes to the build system to enable C++11 features and link Lepton. Unfortunately, due to the restrictions of the UIUC license I am forbidden from distributing either the builds themselves or the modified source tree. Patches are available [here](https://github.com/giacomofiorin/vmd-patches).

I'm changing the doc slightly to reflect the fact that C++11 is an established standard but VMD is lagging behind, while opening the possibility for a savvy user to enable the functionality on their own.

I accidentally pushed to `master` directly, so instead of opening a PR it's just an issue that I'm closing right away.

**Comment by jhenin** [comment]
For reference, this is commit a474c7d0ba1967f01eb1a1672b78415727f2b373
