### ISSUE TITLE
Non-unique bias names

### ISSUE THREAD

**Issue by jhenin** [Colvars/colvars#441]
If two "anonymous" (auto-named) biases of the same type are defined (eg. harmonic1 and harmonic2), and harmonic1 is deleted, then re-created, the new bias is assigned number 2, which creates two biases with the same name. For consistency, I see two possibilities:
- do not decrease the counter when biases are deleted, and assign ever-increasing numbers in order of creation (simple);
- maintain he list of "used" bias numbers and assign new biases the first free number

**Comment by giacomofiorin** [comment]
I vote for the second.  This would also be consistent with how VMD atom
selection objects are allocated.

Our examples could probably use names to encourage people to use them.

I often use "smd" or "us" for certain harmonic restraints to facilitate
analysis.

**Comment by giacomofiorin** [comment]
Well, I mean the first one :-)
