### ISSUE TITLE
Feature f_cv_gradient tries to collect gradients even when not needed, or unavailable. 

### ISSUE THREAD

**Issue by giacomofiorin** [Colvars/colvars#463]
In 9d41a2682f0f5841ecbfa0bf904cb858b18983d7, a condition matching `f_cv_collect_gradient` was substituted with `f_cv_gradient` to allow introspection from the Dashboard, but the two are not the same.

When gradients are collected during a MD simulation, this results in additional processing, because `f_cv_gradient` is on whenever forces are applied. Furthermore, for those variables where part of the computation is off-loaded to the MD engine you get a bunch of warnings like this:
```
Warning: colvar components communicated no atom IDs.
```

The original condition should be reverted, and the Dashboard should use lines like this to request the gradients' collection:
```
cv colvar <xi> set collect_gradient 1
```

**Comment by jhenin** [comment]
Fair points.
