### ISSUE TITLE
Minor initialization glitch

### ISSUE THREAD

**Issue by giacomofiorin** [colvars/colvars#47]
When the module is initialized empty in NAMD, and the first "cv config" command is issued after a "run 0", atomic coordinates are not updated during subsequent runs.  The error is detected by all variables having zero value.

**Comment by jhenin** [comment]
I see this problem happening with current HEAD, but not with NAMD 2.11, so this looks like a fix followed by a regression.

**Comment by jhenin** [comment]
Still current as of today.

**Comment by giacomofiorin** [comment]
Fixed by a73f32f
