### ISSUE TITLE
Read colvars trajectory file in python?

### ISSUE THREAD

**Issue by HanatoK** [Colvars/colvars#478]
I am often using some python scripts to read and parse the .colvars.traj file. Taking pandas as an example:
```python
data = pd.read_csv('test.colvars.traj', delimiter=r'\s+', header=None, comment='#')
```
However, there are multiple issues:
1. Vector values like (such as "(  1 , 0 , 0 , 0 )" in `orientation`) are splitted;
2. No easy way to read column headers;
3. If the order of components in the configuration file is changed, the columns are also changed.
Is there any easy way to read .colvars.traj file in python? A solution may be implement an additional CSV writer as a dummy `bias`, is that possible?

**Comment by giacomofiorin** [comment]
Have you tried using this script?
https://github.com/Colvars/colvars/blob/master/colvartools/plot_colvars_traj.py?raw=true
As far as I can see it addresses all three issues that you mentioned. The main drawback is that the reading loop is coded in Python and is therefore not as fast as it would be with e.g. `numpy.loadtxt()`.

You can also use it as a module, see here:
http://colvars.github.io/colvars-refman-namd/colvars-refman-namd.html#sec:colvars_traj_format

**Comment by HanatoK** [comment]
@giacomofiorin Thanks! I give it a try and it does solve the issues.
