### ISSUE TITLE
NAMD: restart file not read if config is provided as string and not a file

### ISSUE THREAD

**Issue by jhenin** [colvars/colvars#48]
There seems to be a bad interaction between standard NAMD parameter parsing and Tcl scripting.

**Comment by jhenin** [comment]
I see now. The problem is, the restart file is read before any colvars or biases are defined. This can be considered normal behavior. A possible enhancement would be to enable reading of a restart file after cvm initialization, eg. with a scripting command.

**Comment by jhenin** [comment]
Reopen and tag as enhancement.

**Comment by giacomofiorin** [comment]
Implemented by `cv load`
