### ISSUE TITLE
Mutable shared variables

### ISSUE THREAD

**Issue by giacomofiorin** [colvars/colvars#49]
The added support for shared-memory parallelism introduces a problem with shared variables.  These are mostly in the cvm class and are usually read-only so far as multiple threads are concerned.  Two notable exceptions are `cvm::errorCode` and `cvm::depth`.  Currently, neither flag poses a serious risk of data corruption: in NAMD, most errors occur at init time, and all errors result in near-immediate termination of the process.  For `cvm::depth`, I am removing calls to `cvm::increase_depth()` and `cvm::decrease_depth()` from functions that are called simultaneously.

A possible solution is allowing the new dependency tree class (or a similarly-designed base class) handle contain a local errorCode field.  Error codes of multiple children objects could be bitwise-OR'ed by the parent object.

**Comment by akohlmey** [comment]
why not use accessor functions to manipulate them, and use a mutex inside to make them thread safe?

**Comment by giacomofiorin** [comment]
We're using accessor functions already, so that's already done at least.  Using mutex_lock is probably a good option, too, though it will require abstracting them a little if POSIX threads are not available (not sure if that's common any more, though).  Hopefully I'm not neglecting the possibility of some charm++ fun, either...

**Comment by akohlmey** [comment]
you need some threading interface to do concurrent access as it is, and that interface should provide also an API to do mutexes. OpenMP does, for example.

**Comment by giacomofiorin** [comment]
Implemented a lock for the error code, it should behave correctly (the shared error code is bitwise OR'ed automatically).

That leaves open only the problem of parameters like `cvm::depth`, which can not be merged from its different instantaneous values among threads.

**Comment by jhenin** [comment]
My favored option would be to keep one `depth` variable per thread.

**Comment by giacomofiorin** [comment]
This is implemented by commit d6ea2d6.  Leaving the issue open to deal with other shared variables along the way.

**Comment by giacomofiorin** [comment]
A planned increase in data locality should allow threading large atom groups without major problems.
