### ISSUE TITLE
Quaternion constructor calls wrong overload

### ISSUE THREAD

**Issue by jhenin** [Colvars/colvars#492]
https://github.com/Colvars/colvars/blob/434fa73a23abe9c8e3cd2cc3fc0751ba15ac61ba/src/colvartypes.cpp#L148

This will call the constructor from a 3-vector. The construction from Euler angles is implemented by `set_from_euler_angles()`.

I don't think this is used anywhere, so it shouldn't have an impact in practice.

**Comment by giacomofiorin** [comment]
In that case, as with other unused bits of code better delete it. Especially after specific functions for Euler angles were added, it is better to stick to that code path (combining the numerical issues of Euler angles with confusion in the code path isn't good).
