### ISSUE TITLE
ERMSD

### ISSUE THREAD

**Issue by gsabbih6** [Colvars/colvars#495]
How will I use ERMSD collective variables?

**Comment by giacomofiorin** [comment]
Hi Godfred, I presume you mean this type of CV that is provided by PLUMED:
https://www.plumed.org/doc-v2.8/user-doc/html/_e_r_m_s_d.html
https://doi.org/10.1093/nar/gku972

At the moment, Colvars doesn't provide such a function. Are you trying to model a nucleic acid structure specifically or do you have a different problem for which we could suggest alternatives? Which MD engine and computational hardware platform are you using?

**Comment by gsabbih6** [comment]
Hi Giacomo,

Yes I am trying to model a nucleic acid using NAMD on Linux clusters (Huge resources).

Yeah, I read ERMSD is good for RNA dynamics. What would you suggest in this case

thanks

**Comment by giacomofiorin** [comment]
From the look of it it is a good general CV to treat conformational changes in RNA.  I have no reason to question the statement that straight RMSD is inaccurate for RNA, I'm not sure I can suggest quickly anything better for general use. I think rebuilding NAMD with Plumed is worth considering.

If you have a good idea of the conformational change that you're expecting _for your specific problem_, you can try one of the other [available functions](https://colvars.github.io/colvars-refman-namd/colvars-refman-namd.html#sec:cvc_list) in Colvars, optionally customized further with a scripted or custom function. That does not require developing new C++ code.

**Comment by giacomofiorin** [comment]
@gsabbih6 Did you find out how you want to proceed next? Is there anything that can be done within this discussion?

**Comment by gsabbih6** [comment]
I tried others CVs and also patched Namd with PLUMED. Thanks

Godfred
