### ISSUE TITLE
Should cvm::log systematically add a newline?

### ISSUE THREAD

**Issue by jhenin** [Colvars/colvars#503]
I find myself hunting for instances of cvm::log without an explicit "\n", and wondering if there are any cases at all where we don't want it. If not, the function could just add it, and if there are just a handful of cases where we don't want it, that could be a separate option to not add it.

**Comment by giacomofiorin** [comment]
I was thinking the same, so yes.

**Comment by giacomofiorin** [comment]
@jhenin I can't think of any case where I would not want a newline.
