### ISSUE TITLE
Colvars on Gromacs

### ISSUE THREAD

**Issue by jubilantsundar** [Colvars/colvars#504]
I tried using coordNum to drive a separation between protein and ligand.
The protocol itself works but the transition doesn't occur gradually but occurs very quickly in few time steps suddenly. I tried multiple different force constants and simulation length. It only affects when the transition happens but always very quick.
Why is that happening too quickly? Any help.

**Comment by jhenin** [comment]
That will depend on the exact method you use to drive the separation, but also on the parameters of the coordinate. In coordnum, the exponents and the cutoff will make the variable more or less "soft". To get a sense of what parameters will work for you, I recommend loading your trajectories in VMD and inspecting the gradient of the variable using the Colvars Dashboard. This will give you a sense of what forces are applied on what atoms.

**Comment by giacomofiorin** [comment]
To be more complete, if you display the gradients of the CV using the Dashboard, these will also be updated over time as you loop over the trajectory of the simulation that you're analyzing.
