### ISSUE TITLE
Unable to run GaWTM-eABF simulations due to io issue

### ISSUE THREAD

**Issue by HanatoK** [Colvars/colvars#505]
While trying to debug another problem, I run a GaWTM-eABF simulation with NAMD and the following Colvars config block:
```
reweightamd {
    name production_amd
    colvars end_to_end_distance
}
```
and I get the following error:
```
colvars: Error: trying to access an output file/channel from the wrong thread.
```
Before the I/O change there is no such issue, so how can I ensure the output only happens in the main thread?

**Comment by giacomofiorin** [comment]
Can you delete the following?
https://github.com/Colvars/colvars/blob/627e98d8b91901ae3a1a19a7522a290dc8fdd0e5/src/colvarbias_histogram_reweight_amd.cpp#L141-L143
The call to `write_output_files()` was already done separately after the (SMP-parallel) update calls, so you were most likely calling that function twice, once from a thread and once from the main thread.

**Comment by HanatoK** [comment]
@giacomofiorin Thanks! It works, so I suspect that the virtual function `write_output_files()` is called in the main thread only, while other methods could be called in all threads. Is that right? Actually I don't know exactly how SMP works. Do you have documentations or comments about which virtual functions in `colvarbias` are called in the main thread only?

**Comment by jhenin** [comment]
That is because `colvarmodule::calc()` runs in the main thread and calls `write_output_files()` for all biases, safely. Whereas `colvarbias_reweightaMD::update()` can be called in any thread from `colvarproxy_smp::smp_biases_loop()` - so it has to be thread-safe.
