### ISSUE TITLE
PMF calculated returned from Colvars module corrects for PBC?

### ISSUE THREAD

**Issue by Praveen-2k21** [Colvars/colvars#516]
Hi all, 

This is more of a query on how the PMFs are internally calculated by colvars. 

I am running a well-tempered metadynamics of a solute in a membrane. I notice from the plot that time vs collective variable (calculated from .colvars.traj file) that there is a  PBC issue (almost at the same instant the collective variable is moving from one end to other in the graph). Does the Colvars module account for this in the calculation of the PMF? Or do we need to download the trajectory, take care of the wrapping and calculate the PMF using suitable reweighing techniques? 

Best, 
Praveen

**Comment by giacomofiorin** [comment]
Hi Praveen, start with this:
https://colvars.github.io/colvars-refman-namd/colvars-refman-namd.html#sec:colvar_atom_groups_wrapping
and see if anything applies to your setup. There is no general answer to the issue of PBCs. 

Note: I'm assuming NAMD, please report back if different.

**Comment by Praveen-2k21** [comment]
Thank you Giacomo! This was helpful, the issue was sorted out.
