### ISSUE TITLE
Poisson_integrator seems highly inaccurate with 2D path-CV

### ISSUE THREAD

**Issue by gitkol** [Colvars/colvars#518]
Hi, I attached a standard case of 2D path-CV based meta-eABF simulation of a conformational transition with a barrier. If you want to check the details, everything is available at https://www.plumed-nest.org/eggs/23/012/, but I included all the files here required to demonstrate the problem. I ran abf_integrate with -n 100000000, and it gives a perfectly reasonable 2D PMF with a barrier between two minima, one of which is significantly lower than the other. However, if I integrate with poisson_integrator (I am using your latest release) the PMF is completely wrong, in fact it shows a deep minimum where there should be the barrier. I would much prefer using the new integrator, but now I have doubts. The one idea I have is that the binning resolution is vastly different between S and Z, maybe that throws things off, nonetheless, abf_integrator is just fine.

Best regards,

   Istvan Kolossvary

[Poisson_problem.zip](https://github.com/Colvars/colvars/files/11019004/Poisson_problem.zip)

**Comment by giacomofiorin** [comment]
Hi @gitkol, before looking further, can you clarify whether your simulation was done with Colvars or Plumed?

**Comment by fabsugar** [comment]
Dear Istvan,
if you want to have a double check, I have a simple and robust integrator
based on Kinetic Monte Carlo (KMC). The basic principle is similar
to the MCMC integrator of Jerome. I usually run a long KMC (few billions of
steps) at large temperature (e.g. 2000K, which depends on your barriers) to
efficiently sample
all the space.
The integrator is the graf_fes_kmc.py
<https://github.com/FCAM-NIH/FCAM/blob/main/graf_fes_kmc.py> program in:

https://github.com/FCAM-NIH/FCAM

You should eliminate grid points that are not sampled or assign to them a
weight of zero (on the last column).
If you need help let me know,
best,
Fabrizio
