### ISSUE TITLE
Update the Colvars bundled in NAMD

### ISSUE THREAD

**Issue by HanatoK** [Colvars/colvars#519]
@giacomofiorin 
Some users complain about that the GaMD reweighting cannot be used directly unless setting `smp off` in NAMD 3.0b2, but I think the problem has been fixed in the latest Colvars. Is that possible to update the Colvars bundled in NAMD? 

If you don't have time for it, could you provide some hints about how to list the changes in the PR commit message so that I can submit a PR?

**Comment by jhenin** [comment]
@HanatoK Good point. The latest update was merged 3 months ago but that was Colvars v. 2022-05-09. We can create a new merge request, and push for a new beta release soon.

**Comment by jhenin** [comment]
Merge request is there: https://gitlab.com/tcbgUIUC/namd/-/merge_requests/178

**Comment by giacomofiorin** [comment]
Thanks @jhenin for answering promptly. Would you mind editing the commit message in your MR to link in the issues and PRs on this repository?

If you have GitHub's `gh` CLI tool installed, you can peruse the script that I had already used previously to automate the collection. 

```
$ ./devel-tools/print_pr_list.py  --help
usage: print_pr_list.py [-h] [--since SINCE] [--backend {NAMD,VMD,TinkerHP,GROMACS,LAMMPS}]
                        [--state {open,closed,merged,all}]

List of Colvars PRs with the given constraints

optional arguments:
  -h, --help            show this help message and exit
  --since SINCE         List PRs merged this date; default is all (default: None)
  --backend {NAMD,VMD,TinkerHP,GROMACS,LAMMPS}
                        List PRs that affect only this backend; default is all (default: None)
  --state {open,closed,merged,all}
                        List PRs in this state (default: merged)
```

**Comment by HanatoK** [comment]
@jhenin and @giacomofiorin Thank you for your help!

**Comment by jhenin** [comment]
Of course, thanks @giacomofiorin for the heads up! Editing the MR message now.

**Comment by giacomofiorin** [comment]
Adding here the NAMD MR link to track it:
https://gitlab.com/tcbgUIUC/namd/-/merge_requests/178
(requires registration with UIUC)

**Comment by giacomofiorin** [comment]
NAMD MR is merged.
