### ISSUE TITLE
Uniform treatment of forces on "single-particle" vs. normal atom groups

### ISSUE THREAD

**Issue by jhenin** [colvars/colvars#52]
To properly handle fit gradients for all CVCs in an efficient way, we need to know whether atom groups are involved as their COG/COM, or if the cvc depends on individual coordinates in a more complicated way.

A more general approach is to store a vector of weights, providing for all linear combinations of coordinates (or a weight matrix for vector cvcs).

In those cases, we need to store per-group gradients, instead of per-atom.

**Comment by jhenin** [comment]
Side issue to this: treat dummy atoms in a unified way with regular atoms.

**Comment by giacomofiorin** [comment]
This is an easy fix after completing #61
