### ISSUE TITLE
cv load with non-existent file fails silently

### ISSUE THREAD

**Issue by jhenin** [Colvars/colvars#521]
This code in `colvarmodule::setup_input()`
```
    std::istream *input_is = &(proxy->input_stream(restart_in_name,
                                                   "restart file/channel",
                                                   false));
```
has a flag which results in file errors being ignored. @giacomofiorin is this by design, or leftover from testing?

**Comment by giacomofiorin** [comment]
It is supposed to allow the execution of the next block, where `input_prefix` is taken as an explicit file name rather than a prefix:
https://github.com/Colvars/colvars/blob/05efce05749a76df28773bdd6ee0ec8c90abbfa6/src/colvarmodule.cpp#L1294-L1302
If the explicit file name is also not there, this time an error is raised.

Can you please describe in more detail the situation where this logic fails?

**Comment by jhenin** [comment]
Here the test `if (input_is->bad()) {` is not triggered - after checking, in this case it seems both good() and bad() return false! I'm perplexed.
After this error I get bad() == false, good() == false, **fail() == true**, and eof() == false.
So fail() gives the correct information. However this combination of return values for the accessors is nowhere in the table here:
https://en.cppreference.com/w/cpp/io/basic_ios/fail
We could fix this by testing for fail(), or more simply, for !good(). I wish gcc and cppreference could agree on this though.

**Comment by giacomofiorin** [comment]
I'm confused, what is correct? The current code in `master`, or the suggestion to use fail()?  I'm fine with the change if needed.

Back to the use case that triggered the error: is this a situation where the state file is accidentally missing or something different?

**Comment by jhenin** [comment]
Sorry, forget about the "correct behavior" remark, at some point I though the compiler misbehaved but it doesn't.

I think the most robust test is `not good()`, if we don't want to treat `fail()` separately.

**Comment by giacomofiorin** [comment]
Ok, `! good()` sounds okay to me. Please open a PR to that sense.

Also, you still haven't answered the question:  is this a situation where the state file is accidentally missing or something different?

**Comment by giacomofiorin** [comment]
P.S. There are many instances where the bit being checked is `bad()`, and those would need to be replaced as well.

Earlier on you had some strong opinions about the design of the I/O:
https://github.com/Colvars/colvars/pull/481#discussion_r873952043
So the most practical approach for me is to let you pick any design choice you think appropriate when fixing this issue.

**Comment by jhenin** [comment]
That's fair!

**Comment by jhenin** [comment]
Important documentation from cppreference.com:
![image](https://user-images.githubusercontent.com/4518166/230643520-c49f38ef-df65-44da-a546-d779df8c810a.png)

I'm just going to replace bad() with fail().

**Comment by giacomofiorin** [comment]
I'm still confused. Although the calling code is using `bad()`, the file opening functions uses `! good()` internally, and that should catch pretty much anything:
https://github.com/Colvars/colvars/blob/05efce05749a76df28773bdd6ee0ec8c90abbfa6/src/colvarproxy_io.cpp#L173-L176
How are you not getting an immediate error at that point?

**Comment by jhenin** [comment]
> colvarproxy::input_stream() uses ! good() internally

Only if `error_on_fail` is `true`.
