### ISSUE TITLE
Need regression test for CVCs with sub-CVCs

### ISSUE THREAD

**Issue by jhenin** [Colvars/colvars#53]
That is, alpha and dihedralPC. There could be subtle issues in the future wrt the deps system if it assumes a strict hierarchy bias-cv-cvc-atom group.

**Comment by jhenin** [comment]
We also need a regression test for extended-Lagrangian colvars.

**Comment by giacomofiorin** [comment]
This can be dealt with by not allocating any groups within the nested CVCs, but call their functions onto the group allocated by the parent CVC.

**Comment by jhenin** [comment]
CVCs in CVCs need to be flattened: instead of allocating a CVC, call functions from that CVC.

**Comment by giacomofiorin** [comment]
Extended Lagrangian: b2dd73c
Alpha component: b31fc30

Jérôme, can you add one for dihedral PC and close the issue? Thanks.

**Comment by jhenin** [comment]
I will.

**Comment by giacomofiorin** [comment]
Can we close this?

**Comment by jhenin** [comment]
See pull request: https://github.com/Colvars/colvars/pull/167
