### ISSUE TITLE
RMSD is too slow

### ISSUE THREAD

**Issue by HanatoK** [Colvars/colvars#540]
I am running TMD simulations to align structures with the RMSD CV. It is slow and I am trying to figure out why. I have tried to write a simple implementation for comparison (see https://github.com/HanatoK/colvars/blob/eigen_rmsd/src/colvarcomp_eigen_rmsd.cpp). Using the STMV test case in NAMD on my laptop and defining the RMSD with 89,212 atoms, I have found that the simulation speeds are about:
- 1.34 ns/day (without RMSD and Colvars)
- 1.21~1.22 ns/day using my own implementation
- 0.66~0.67 ns/day using the original RMSD implementation
- 0.94~0.95 ns/day with loop unrolling in `colvartypes.cpp` (see https://github.com/HanatoK/colvars/commit/d381f194ba7ea0859b3951a3c1052227acbb3b7b). The default compilation flags seem unable to unroll the loop.

Furthermore, the `request_group1_gradients` and `request_group2_gradients` seem to be redundant in most cases (https://github.com/Colvars/colvars/blob/master/src/colvarcomp_distances.cpp#L1046-L1050). In my TMD simulation, even if I comment the two lines `atoms->rot.request_group1_gradients(atoms->size());` and `atoms->rot.request_group2_gradients(atoms->size());`, I can still get the gradients correctly if I enable `debugGradients On` and the simulation is much faster. I know they may be important for ABF which requires the total force, but if the total force is not required, they could be disabled.

Is it possible to optimize the RMSD code?

**Comment by HanatoK** [comment]
Some thoughts:

- The derivative of RMSD with respect to atom coordinates does not require calculating the derivatives of max eigenvectors. Thus the calculation of `dS_1` and `dQ0_1` can be simplified.
- Even in non-RMSD cases, the two loops `for (ia = 0; ia < dS_1.size(); ia++) {...}` and `for (ia = 0; ia < dS_2.size(); ia++) {...}` in `calc_optimal_rotation` are big overheads. In general, Colvars loops over N atoms there, but it will loop over N atoms again in loops like 
```C++
for (size_t ia = 0; ia < atoms->size(); ia++) {
    (*atoms)[ia].grad = (dxdq0 * (rot.dQ0_2[ia])[0]) +
                        (dxdq1 * (rot.dQ0_2[ia])[1]) +
                        (dxdq2 * (rot.dQ0_2[ia])[2]) +
                        (dxdq3 * (rot.dQ0_2[ia])[3]);
  }
```
in `colvar::euler_theta::calc_gradients()`. I think the calculation of `dQ0_1`, `dQ0_2` and similar variables could be implemented as a member function of `colvarmodule::rotation`, for example, `cvm::rvector cvm::rotation::dQ0_1(size_t ia)`, in order to reduce the number of expensive loops over all atoms.

**Comment by giacomofiorin** [comment]
@HanatoK You brought many valid points, most of which reflect issues arising from very old design choices (2005-2006, i.e. well before Colvars' first public release with NAMD 2.7).

In many of these cases, you would probably be distributing the force field computation over many CPU or GPU cores, and the communication overhead would be also significant. This needs to be addressed as well, and has been discussed already. You should expect some improvements coming to `colvarproxy` after the [MDModules-compatible GROMACS interface](https://gitlab.com/gromacs/gromacs/-/issues/3357) is finalized. 

That said, certain incremental improvements that are well defined in scope (at least within the library) and don't affect portability should be easy to integrate. Would you like to open a PR for the loop unrolling? I don't know how much impact would it have on fewer RMSD atoms and a distributed computation, but it surely can't hurt.

Lastly, an important usage note. When the RMSD is used only for a static restraint in NAMD, my best recommendation would be using `extraBonds`. A RMSD computed over many atoms may fail to detect a local conformational change in a specific subset of those atoms. The `extraBonds` restraints would keep every local structure restrained by construction, in many cases being more useful (in addition to being faster).
