### ISSUE TITLE
"trying to access an output file/channel from the wrong thread." when using writeHillsTrajectory

### ISSUE THREAD

**Issue by HanatoK** [Colvars/colvars#544]
I have tested the official NAMD 3.0b3 binary and also the latest Colvars master branch. When using `writeHillsTrajectory on` in metadynamics, I encounter the following error:
```
colvars: Error: trying to access an output file/channel from the wrong thread.
FATAL ERROR: Error in the collective variables module (see above for details)
FATAL ERROR: Error in the collective variables module (see above for details)
```
Please see the following attachment for a test case.
[apathCV_example_bug.tar.gz](https://github.com/Colvars/colvars/files/11769146/apathCV_example_bug.tar.gz)

**Comment by giacomofiorin** [comment]
Thanks for catching this and the quick fix!

@ThaNikkitz It may take a while for the updated Colvars snapshot to make it into the NAMD distribution. A quick workaround for the error that you are experiencing would be to add this line:
```
smp off
```
at the top of the Colvars config file, which would force all Colvars objects to run on the first thread. If you have a very complex input (many CVs or components) this may lose some performance, but at least it would circumvent the bug without recompilation.
