### ISSUE TITLE
Control the update of the .colvars.traj file

### ISSUE THREAD

**Issue by fhh2626** [Colvars/colvars#551]
Hi all,

Colvars scripting is very good. However, it is very common to do something like:
```tcl
for {set i 0} {$i < $some_number} {incr i} {
    # ...do something
    run N
}
```
and the .colvars.traj file is updated every `run N`. This is terrible when N is small, especially when `N=0`
For example, I got something like
```
# step         distance               RMSD                  
           0    9.04976638203283e+00   1.20417334952233e+01 
        2500    8.29272907478288e+00   1.18817457132166e+01 
        2500    8.29272915734579e+00   1.18817458367923e+01 
        5000    9.31117930711349e+00   1.18364429998855e+01 
        5000    9.31117939394333e+00   1.18364431542536e+01 
        5000    9.31117939394333e+00   1.18364431542536e+01 
        5000    9.31117939394333e+00   1.18364431542536e+01 
        5000    9.31117939394333e+00   1.18364431542536e+01 
        5000    9.31117939394333e+00   1.18364431542536e+01 
        5000    9.31117939394333e+00   1.18364431542536e+01 
        5000    9.31117939394333e+00   1.18364431542536e+01 
        5000    9.31117939394333e+00   1.18364431542536e+01 
        5000    9.31117939394333e+00   1.18364431542536e+01 
        5000    9.31117939394333e+00   1.18364431542536e+01 
        5000    9.31117939394333e+00   1.18364431542536e+01 
        5000    9.31117939394333e+00   1.18364431542536e+01 
        7500    7.76836690884596e+00   1.13542897733702e+01 
        7500    7.76836693566903e+00   1.13542897976220e+01 
```

Is it possible to ask colvars to not update the .colvars.traj file when a `run N` is achieved?

Thanks,
Haohao

**Comment by giacomofiorin** [comment]
@fhh2626 The case `run 0` in NAMD covers several different use cases, including those where you are swapping coordinates, and the colvars change accordingly (no repetition). Getting each use case right may be difficult.

How about a post-processing step where the overlapping steps are removed, as we already do in `plot_colvars_traj.py` when concatenating files (only for the first and last step  so far)?

**Comment by jhenin** [comment]
One relatively low-impact way to achieve that would be a scripting command to set the colvarsTrajFrequency parameter. Setting it to zero will disable traj output, and that can be reverted by making it nonzero again.

**Comment by fhh2626** [comment]
@giacomofiorin Yes, we can of course do a post-processing, but it will be very nice if we have something like `cv updateoutput 0` and `cv updateoutput 1` before and after `run N`.

**Comment by HanatoK** [comment]
@fhh2626 
Another way is writing your own trajectory file instead of using `.colvars.traj`. You can put something like
```tcl
set my_traj [open "test.traj" "w"]
puts -nonewline $my_traj [cv printframelabels]
```
before your loop, then call `puts  -nonewline $my_traj [cv printframe]` in your loop, and finally close the file after the loop.

**Comment by giacomofiorin** [comment]
@fhh2626 Did this suggestion work?

**Comment by fhh2626** [comment]
> One relatively low-impact way to achieve that would be a scripting command to set the colvarsTrajFrequency parameter. Setting it to zero will disable traj output, and that can be reverted by making it nonzero again.

Yes, I will close this issue.
