### ISSUE TITLE
Stop subtracting applied forces from total forces

### ISSUE THREAD

**Issue by giacomofiorin** [colvars/colvars#56]
It is becoming increasingly difficult (e.g. in message-passing parallelism) to perform an easy bookkeeping of the forces applied to each atom via different code paths (individual atoms vs. scalable groups).
The most practical solution is to stop reporting "system forces" acting on individual collective variables, and report instead for each variable the total force alongside the applied force. This will create the following changes in behavior:
1. The boolean flag `outputSystemForce` of a colvar should be deprecated and replaced by `outputTotalForce`. When a colvar's configuration has `outputSystemForce` set to `on` (it is `off` by default), the code should trigger an error condition and prompt the user to to change the configuration to `outputTotalForce`. No changes are needed to `outputAppliedForce`.
2. The ABF object must still subtract its own biasing force from the total force to perform TI-based free energy calculations (this is actually the original requirement for system forces in the first place). Therefore, it will carry out this subtraction internally (currently, this is done at the level of the entire code). To keep track of the time evolution of the system force, `outputSystemForce` can be enabled _in the context of ABF only_. 
3. Potentials of mean force calculated by ABF or by other TI-based integration of the system forces will be fully consistent with the output of umbrella sampling and metadynamics.

**Comment by giacomofiorin** [comment]
It is worth noting that as of NAMD 2.11 external forces can be applied on group COMs through tclForces: these are not being identified as such, and are not subtracted from the total force, breaking with the behavior for forces applied to individual atoms.

**Comment by giacomofiorin** [comment]
Added TODO: tutorial updates

**Comment by jhenin** [comment]
Implemented by e46aa07f025aad2a3289ac94655344d564be1e60 and e4fe31b8ffbf62104a8cea2d10d77a27d6d481ef.

Some fixes needed for regtests, and doc + tutorial updates. And inform the community of users about it.

**Comment by jhenin** [comment]
Incidentally, this results in significant performance improvements for small systems like Ala10. It can't be bad for scalability, either.

**Comment by jhenin** [comment]
While it is difficult to keep track of forces at the atom level, we do it at the colvar level (eg. outputAppliedForce), so we could still calculate a system force at the colvar level. The question is, what would this be useful for? Applications with a specific need for a system force may request both quantities and subtract them.

**Comment by giacomofiorin** [comment]
I like that, after considering that we need to update the reg tests, you removed the "quick" label :-)

I agree on dealing with each application that needs a system force on a case-by-case basis.  As mentioned before, we cannot track forces applied on COMs through tclForces any more, and the availability of a "system force" cannot be guaranteed any more.

Two important uses of the "system force" are unconstrained thermodynamic integration (Figure 3 of our paper), and external uses of the system forces (binning, etc).  For the latter case, we can always report total and applied forces, but for unconstrained TI (i.e. ABF with `applyBias off`) we need to subtract the applied force of the colvar, not just the ABF force.  I'm fine with actually making a derived bias that has a different name than ABF, though, to avoid confusion.

**Comment by jhenin** [comment]
This makes me consider again an option I had in mind earlier, which was to add a form of 'ignoreBias' option to ABF, where forces from the given bias(es) on the relevant colvars will not be part of the system force. In the case of metadynamics + TI, that would be the forces from metadynamics.

**Comment by giacomofiorin** [comment]
That sounds just like what we need.  My only suggestion is rather small, and is to name this differently from ABF since it's not ABF after all, though it is based on the same formalism.

**Comment by jhenin** [comment]
If users do ABF with walls within the biased boundaries, then it's still ABF and they will need this feature. I worry that creating a different bias will just duplicate code - unconstrained TI is not ABF, but it is entirely a subset of ABF functionality, it's ABF with some bits disabled.

**Comment by giacomofiorin** [comment]
You're right, we will also need to keep track of the wall forces for plain ABF.

FYI, the changes in the `colvarbias` class and its derivatives now allow full reuse of base-class code without duplication (see `bias-base` branch).

Currently, this is useful in the I/O functions (that were the worst offenders in terms of duplicated code) but can be used in any derived class.  Now it's possible to implement harmonic wall biases (issue #58) by inheriting `colvarbias_restraint` and `colvarbias_restraint_k` (or even better: `colvarbias_restraint_k_moving` to get the target and restraint TI functionality) but not the `colvarbias_restraint_centers` class, because there are two boundaries instead of a center.

**Comment by jhenin** [comment]
That sounds great, I need to look into it for the walls.

For ABF/TI though, I suppose you wouldn't derive a class from colvarbias_abf that would implement less? It would seem logical to do the reverse and extract the TI functionality into a base class, but I'm not sure I want to do that work when we already have what we need working (or will have once ignoreBias is implemented). Here the inheritance only seems necessary to me if we wanted to derive two different classes from the same base.

**Comment by giacomofiorin** [comment]
For the time being let's go with the ABF flag, but I am happy to implement the base class relatively soon.  There are several protocols (not only the metadynamics-based one but also the CHARMM-style Hamiltonian-exchange + TI) that would need a TI base class.

It is actually quite easy now to move the TI code into a base class and then call it from inside the ABF class.  For `update()`, the first part can be cleanly moved to become the base class's own `update()` function, and ABF can just call it without any change in the current behavior.

**Comment by jhenin** [comment]
Once ABF can subtract forces for selected biases, we should recover the functionality of NAMD regtest 5, which has a harmonic bias interfering with ABF.

**Comment by giacomofiorin** [comment]
Commit 8c3885c (option `subtractAppliedForce`) implements a partial recovery of system force definition in the simple case where the applied force comes entirely from colvar biases.  However, in regtest 5 the new quantity (total_force - applied_force) differs from the previous system force by about ~10^-6 kcal/mol/Å between NAMD CVS (2016-09-29) and the same NAMD compiled with the new Colvars snapshot.

**Comment by giacomofiorin** [comment]
The inconsistency in regtest 5 is easily explained by the inaccuracy of the total force calculation (see issue #83). This issue is now fixed.
