### ISSUE TITLE
Writing Custom Function in NAMD Colvar Configuration

### ISSUE THREAD

**Issue by naliio** [Colvars/colvars#565]
Hi,

I'm aiming to set the colvar value to 2 when the atomic distance <= 3.3, and to 1 when  3.3 < distance <=4, and 0 when distance >4. I tried many times but they all reported `errors` regarding my writing of colvar. One of my attempts is as follows:

<pre>
colvar {
    name hb1
    customFunction {2 if  x <= 3.3, 1 if 3.3 < x <= 4, 0 if  x > 4}
    distance {
        name x
        group1 {atomNumbers 21   }
        group2 {atomNumbers 624  }
    }
}
</pre>

How should I modify my writing of colvar？Thank you very much for your assistance.

**Comment by HanatoK** [comment]
Hi @naliio, the implementation of `customFunction` relies on the [Lepton library from openMM](https://github.com/openmm/openmm/tree/master/libraries/lepton). Unfortunately it does not support operators like `<=`, `<` and `>`, and I cannot find its latest manual. There is [an old one](https://usermanual.wiki/Document/Lepton20Users20Manual.510913181.pdf), in which you can find the `step` function and it may help. For example, if you want to obtain 0 if x > 4, you can write `step(-(x-4)).`

**Comment by naliio** [comment]
Thank you very much. Step function is a good idea.
