### ISSUE TITLE
Projecting PMF along a new collective variable?

### ISSUE THREAD

**Issue by Praveen-2k21** [Colvars/colvars#567]
Hi all, 

Using NAMD and Colvars, I have run Well tempered metadynamics simulation for my system and I have obtained the PMF as a function the collective variable which was biased (say CV1). Now I was wondering if there is a way to project this PMF & CV1 along a new collective variable CV2 and have a 2D PMF? I can only calculate CV2 from the dcd file. The bottleneck here I am facing is the relationship between CV1 and CV2 may not linear, also the mapping between CV1 and CV2 would be many-to-many, and if I am not wrong this will require some kind of reweighting. Request your suggestion please?

**Comment by jhenin** [comment]
Hi Praveen,
indeed this is a reweighting question. Assuming your system is well-sampled and the DCD file contains enough frames, you can estimate the pair density of (CV1, CV2) by histogramming or KDE, while reweighting samples to remove the metadynamics bias on CV1 (see https://pubs.acs.org/doi/10.1021/acs.jctc.9b00867 for example). Then, Boltzmann-inverting the result gives you a 2D free energy surface. Be aware that there are a series of assumptions involved in this process. The resulting FES is unlikely to be as accurate as one obtained from 2D enhanced sampling.
Jérôme
