### ISSUE TITLE
Common regtests for all backends

### ISSUE THREAD

**Issue by jhenin** [colvars/colvars#57]
New directory structure: 
`colvars/tests/<nnn>_<title>/<name>.in`

By default, this is enough to run a test with default VMD/NAMD/LAMMPS input, eg:
`namd/tests/library/Common/test.namd`

Test dirs may contain an extra input file, eg:
`namd/tests/library/<nnn>_<title>/<name>.namd`which may source the common input.

Backend-specific inputs (ie scripted) go to `<backend>/tests/interface`.

**Comment by giacomofiorin** [comment]
A possible addendum for this issue: all reg tests should ideally contain checkpoints, i.e. there should also be a file:
`namd/tests/library/Common/testres.namd`
which is identical to `namd/tests/library/Common/test.namd` except for containing instructions to continue the previous calculation.

**Comment by giacomofiorin** [comment]
Commit f5719f7edac1dd7cbc4d2b996b6d6d8b8dc0c046 implements the majority of this.  Only remaining are the implementations of the input for VMD and LAMMPS.

**Comment by giacomofiorin** [comment]
As it turns out the tests for VMD would be rather different, and commit ef18210 implements this fir LAMMPS
