### ISSUE TITLE
Drop Oracle/Sun compiler from CI tests?

### ISSUE THREAD

**Issue by giacomofiorin** [Colvars/colvars#595]
Developer Studio is a commercial compiler that back in the day used to provide informative warning messages. However, it has a few caveats:
- Restrictive license forces us to use secrets in CI; we're already doing that for NAMD and VMD, but the fewer the better.
- Does not support anything more recent than C++11, and there seem to be no plans to change that.
- The logic of its warnings about function hiding (one of its most useful IMO) starts getting a bit fragile when both `virtual` and `override` are used in the same class (even if not on the same function).

Open source tools like `clang-tidy` provide a useful alternative, especially if one fine-tunes their scope to avoid it being too aggressive.

Thoughts?

**Comment by jhenin** [comment]
I see no problem with dropping it.

**Comment by giacomofiorin** [comment]
The Sun compiler was still useful in a couple of cases. It can probably be superseded by clang-tidy, but it's much less picky about it.

Perhaps the best is to keep using it until it can no longer keep up with the C++ standard.
