### ISSUE TITLE
issue of integrate_potential::get_grad for non-periodic cv

### ISSUE THREAD

**Issue by zwpku** [Colvars/colvars#621]
I was doing ABF simulations in NAMD using a non-periodic CV and restarting from a previous run. It seems that the function,  invoked by pmf->set_div(), 

https://github.com/Colvars/colvars/blob/67244e8df8385e784aef63fb29663d462fed1707/src/colvargrid.cpp#L667-L676

is unsafe, since Line 673 will invoke the function
https://github.com/Colvars/colvars/blob/67244e8df8385e784aef63fb29663d462fed1707/src/colvargrid.h#L58-L65
which will return an incorrect address `addr`  when the index `ix` is on the edge of the grid, e.g. ix=(-1,0).  This may lead to the access of wrong address in memory (maybe harmless though), or a fatal error when debug mode is on (my case). 

Would it be better to implement `get_grad` as below?

        size_t count, i;
        bool edge = gradients->wrap_edge(ix); 
        if (!edge) {
            if (gradients->samples) {
              count = gradients->samples->value(ix);
            } else {
              count = 1;
            }
            cvm::real fact = 0.0;
            if (count) fact = 1.0 / count;
            cvm::real const *grad = &(gradients->value(ix));

            for ( i = 0; i<nd; i++ ) 
              g[i] = fact * grad[i];
      } else {
            for ( i = 0; i<nd; i++ ) 
              g[i] = 0.0;
        }

**Comment by jhenin** [comment]
Thank you @zwpku !
