### ISSUE TITLE
Redundant link to updated doc in manual?

### ISSUE THREAD

**Issue by jhenin** [Colvars/colvars#633]
This mention at the end of the manual seems redundant with the links at the top.
https://github.com/Colvars/colvars/blob/2cb3e2dd5e5671399885653c7d6264c986637309/doc/colvars-refman-main.tex#L7417

They refer to the very same links `https://colvars.github.io/\cvreleaselabel/colvars-refman-{CODE}.html`

**Comment by giacomofiorin** [comment]
Okay with me to delete them.

**Comment by giacomofiorin** [comment]
For the record, we had those links back when the Colvars doc was embedded in the NAMD manual, and we wanted folks to click on those links.
