### ISSUE TITLE
CI test uses Clang 14 when the action name mentions Clang 16

### ISSUE THREAD

**Issue by jhenin** [Colvars/colvars#646]
In the action named  "Clang 16 address sanitizer"

https://github.com/Colvars/colvars/blob/7ee529fe17a47bf6b1df60dd0442782313c74f14/.github/workflows/test-library.yml#L251

I'm unsure if the name or the clang version should be changed.

**Comment by giacomofiorin** [comment]
I do not believe that's true. The build/test are done using the container instead of the Microsoft-provided Ubuntu VM.

I'll remove that command, which is a leftover from a copy-paste, so that it doesn't confuse people.
