### ISSUE TITLE
Use only "enabled" flag for static and user properties

### ISSUE THREAD

**Issue by jhenin** [colvars/colvars#66]

**Comment by jhenin** [comment]
I'm assigning myself, but that's also a request for others :-)

**Comment by jhenin** [comment]
In practice, that means removing the current usage of `provide(...)` for static properties. That function should be there to make dynamic properties available. Static properties should be `set_enabled`.

**Comment by giacomofiorin** [comment]
Can you clarify the criteria by which you classify features as dynamic, static or user?  I see that after commit b4c570a there are still several calls to `provide()` for features that I would expect to be "static", e.g. `f_cvc_inv_gradient`.  Are more changes needed?

**Comment by jhenin** [comment]
f_cvc_inv_gradient counts as a mutable feature: it is under the control of a dependency system to be enabled only when necessary.

The next changes are going to finally make these different classes of features explicit, because I realize it's far from clear now. I am introducing three feature types: static, user, and mutable.

**Comment by jhenin** [comment]
Please see commit 76533d61692574959a607c29925d419fd30fc3ba. Each call to init_feature should be completed with a type. Then the dependency system can make better informed decisions based on that (not implemented yet, will do once the types are assigned).

**Comment by jhenin** [comment]
Note the three feature types are documented in the header to `colvardeps.h`.
