### ISSUE TITLE
Rename cvm::deps to colvarmodule::deps (or colvarmodule::everything to cvm::everything?)

### ISSUE THREAD

**Issue by giacomofiorin** [colvars/colvars#67]
Doxygen interprets `cvm::` and `colvarmodule::` as two distinct namespaces.  The quickest fix would be to use `colvarmodule::deps` instead of `cvm::deps`.

**Comment by jhenin** [comment]
Fixed by renaming the class colvardeps and removing from the cvm namespace (c33ad31c94fc021f175e0288f75ff0b334310c63).
