### ISSUE TITLE
dA/dLambda outputs: trajectory file and dispersion

### ISSUE THREAD

**Issue by EzryStIago** [Colvars/colvars#678]
When estimating a restraint free energy by changing the force constant (section 6.5.3 in the user guide), dA/dLambda is accumulated and printed in the log file (without any measures of dispersion).

It would be nice to have:
1. the raw dA/dLambda samples (with some user-specified frequency)
2. a standard deviation (or variance) for the accumulated dA/dLambda

This would streamline my RFEP calculations (and simplify the SAFEP tutorial as well).

**Comment by jhenin** [comment]
Thank you for the good suggestion. I think the best implementation will be for the bias to output dV/dlambda to the colvars.traj file.

**Comment by jhenin** [comment]
See PR #753

**Comment by jhenin** [comment]
Solved by https://github.com/BranniganLab/safep/pull/56
