### ISSUE TITLE
sh: 15: hash: Illegal option -t

### ISSUE THREAD

**Issue by ljh433** [Colvars/colvars#693]
when i Patch Gromacs with Colvars (sh ./colvars-master/update-colvars-code.sh ./gromacs-2020.6)，there is an error：./colvars-master/update-colvars-code.sh: 15: hash: Illegal option -t. May I ask what the reason is. How to solve this problem？

**Comment by jhenin** [comment]
It looks like you are using an incompatible version of `sh`. Try calling the script with `bash`, or just execute the script without specifying the shell.

**Comment by giacomofiorin** [comment]
@ljh433 Were you able to try a different shell?
