### ISSUE TITLE
Jacobian term not computed when no ABF bias is defined

### ISSUE THREAD

**Issue by jhenin** [colvars/colvars#71]
That bug was caused by the tasks for the Jacobian derivative being handled too specifically within the ABF bias. Fixed by the switch to the deps system.

**Comment by jhenin** [comment]
Note: this issue was created to document the bug for future reference, aven though it is already fixed. I suggest we make a rule of this.

**Comment by giacomofiorin** [comment]
Agreed.  Let me just add that regtest 3 was affected to search for it
again.  Was it 10 too?
