### ISSUE TITLE
Inconsistent GETCWD in src/colvarbias_meta.cpp can cause underfined behavior

### ISSUE THREAD

**Issue by al42and** [Colvars/colvars#726]
In src/colvarbias_meta.cpp, there's `GETCWD(BUF, SIZE)` macro used to wrap `getcwd` function to put current working dir into `BUF`. However, when `std::filesystem` is available, a different implementation is used, which does not change `BUF` but instead returns a temporary C-string: https://github.com/Colvars/colvars/blob/0e0ce447630e95f2cd0322b1699e7f60b526ef9f/src/colvarbias_meta.cpp#L25C1-L30C7

This is not ok with [how `GETCWD` is later used](https://github.com/Colvars/colvars/blob/master/src/colvarbias_meta.cpp#L1743-L1754):

```cpp
    char *pwd = new char[3001];
    if (GETCWD(pwd, 3000) == nullptr) {
      if (pwd != nullptr) { //
        delete[] pwd;
      }
      return cvm::error("Error: cannot get the path of the current working directory.\n",
                        COLVARS_BUG_ERROR);
    }

    replica_list_file =
      (std::string(pwd)+std::string(PATHSEP)+
       this->name+"."+replica_id+".files.txt");
```

The conditional will never be false, but `pwd` will not be initialized; thus so `std::string(pwd)` later is UB.

**Comment by giacomofiorin** [comment]
Thanks!  Will fix it here and include it in the GROMACS 2024 bugfixes as well as the Colvars lib update for 2025.
