### ISSUE TITLE
Format of number in the ABF state file messes up regtests

### ISSUE THREAD

**Issue by giacomofiorin** [colvars/colvars#76]
Starting from commit f20f0c4 the multicol gradients output is now formatted in scientific notation, including the number 0. The number of character used per gradient, and the number of gradients per line in the file, is different from previous versions, creating a difference for spiff.

**Comment by jhenin** [comment]
Ah yes, that was done for compactness and consistency with other types output, but I don't have very strong opinions on this. Do you? If we keep this, I'll update the regtest output.

**Comment by giacomofiorin** [comment]
I'm OK with the current output. I just had an issue come up when I was trying to compare a new batch of regtest inputs between 2.11 and now. I'll upload the inputs, and we can discuss afterwards which version of the code should generate the reference outputs.

**Comment by giacomofiorin** [comment]
Superseded by updated reference files 7f28747
