### ISSUE TITLE
Simplify read_restart()

### ISSUE THREAD

**Issue by jhenin** [colvars/colvars#80]
read_restart() methods contain mostly duplicated and boilerplate code. Use a parent class implementation and perhaps helper functions to make them shorter and cleaner.

**Comment by giacomofiorin** [comment]
This is pretty much done already in the `bias-base` branch. I'm only delaying its merge `master` because of the magnitude of the changes, and the fact that we're due for an update with version-bases programs (VMD, NAMD).

Is there a specific feature that should be added to `bias-base`?

**Comment by jhenin** [comment]
Good, that takes care of some of the shared code. It leaves what I called the boilerplate, which is this kind of error handling:
```
  if (! gradients->read_raw(is)) {
    is.clear();
    is.seekg(start_pos, std::ios::beg);
    is.setstate(std::ios::failbit);
    return is;
  }
```
There are tons of copies of this little block, it adds up.

**Comment by giacomofiorin** [comment]
Yes, I agree. This block can be collapsed into a single colvargrid member function, will add it at the next opportunity.

**Comment by giacomofiorin** [comment]
Done by 833b3b88cc37f577b5a342e0b2b62eea75dac87b.

FYI, there weren't "tons of copies" of the repeated snippet.

Actually, not many other occurrences outside of the ABF class, which now has four instances of it (samples, gradients, z-samples, z-gradients).  Metadynamics needs a different kind of test to handle reading in multiple-replica information, and the restraint classes need to distinguish between "restraint" and "harmonic".
