### ISSUE TITLE
Previous-step total forces are calculated using current-step inverse gradients

### ISSUE THREAD

**Issue by giacomofiorin** [colvars/colvars#83]
To keep parallel performance high, total atomic forces cannot be communicated to Colvars until all calculations of a MD step come in.  For this reason, total atomic forces are always those from the _previous_ time step, and the total colllective force at step 0 is not available.

The total atomic forces are used to compute total collective forces (labeled as "ft" in the `colvars.traj` output) by using the inverse atomic gradients (IAGs).  However, the IAGs are typically calculated using atomic gradients from the _current_ time step.  Such inconsistency creates a small error, which has affected total force calculation and ABF starting from early versions of the Colvars module.  The same is true for the Jacobian term, which uses the _current_ value of the collective variable. 

A solution to this can be to compute the IAGs and the Jacobian term, store them in the `atom_group` container (see also #61), and use them at the beginning of the next MD step.

**Comment by jhenin** [comment]
Presumed fixed by 833c5803f43cc4d6b300fd470673288045f98369.
